### ISSUE TITLE
MockDirective does not support Angular Structural Directives

### ISSUE THREAD

**Issue by workswithweb** [ike18t/ng-mocks#1]
MockDirective does not support Angular Structural Directives. Can you please add support

**Comment by conor-mac-aoidh** [comment]
+1

I would also like this feature. Currently, I get this error using `MockModule` on a module that imports the `CommonModule`:

```
Failed: No Directive annotation found on [NgClass, NgComponentOutlet, NgForOf, NgIf, NgTemplateOutlet, NgStyle, NgSwitch, NgSwitchCase, NgSwitchDefault, NgPlural, NgPluralCase]
```

**Comment by ike18t** [comment]
@conor-mac-aoidh What if, as an alternate solution to that problem, the real CommonModule gets provided so you can test angular behavior side-effects?

**Comment by conor-mac-aoidh** [comment]
@ike18t I am importing `CommonModule` in my test. I think the problem arises because the module I am mocking using `MockModule` also imports `CommonModule`

**Comment by ike18t** [comment]
@conor-mac-aoidh 

Out of curiosity, are you re-exporting CommonModule by chance?  Currently MockModule is recursively iterating through the module's imports (which would include exports).  Now that I think about it...that is probably not what it should be doing, but iterating over the exports instead.

Thoughts?

**Comment by conor-mac-aoidh** [comment]
@ike18t I am not re-exporting `CommonModule` in the module I am trying to mock, I am just importing it.

I agree with your assessment, only the exports of each module should be mocked. That should solve the issue of mocking a module that imports `CommonModule`, but it doesn't fix the structural directives issue in #1. Maybe I should open a new issue for this?

**Comment by ike18t** [comment]
@conor-mac-aoidh That would be great.  Thanks!

**Comment by ike18t** [comment]
Structural directive support:  050e70ca22d810b1f9a8a8e2ff38253808eb42a6
