### ISSUE TITLE
Mocked component and host decorator

### ISSUE THREAD

**Issue by kenborge** [ike18t/ng-mocks#10]
If you have 2 nested components like this
```
<outer>
  <inner></inner>
</outer>
```
And the inner component uses a host decorator to inject the outer component in it's constructor
`constructor( @Host() public outer: OuterComponent ) { }`

When you want to test the inner component it does not seem like it's possible to mock outer component in the tests as the component declared in the TestBed `MockComponent(OuterComponent)` is not found and injected into the constructor of the inner component. 

Is there any way to make this work?

**Comment by ike18t** [comment]
https://stackblitz.com/edit/bah?embed=1&file=app/hello.component.spec.ts

Here's an example I whipped up really quick.

The meat of it is:
      providers: [ 
        { 
          provide: AppComponent, 
          useClass: MockComponent(AppComponent)
        } 
      ]

**Comment by kenborge** [comment]
I didn't know you could provide components, that's cool. But i modified your code to be closer to mine and it still didn't work.
The main difference is my "hello" component is projected content. So i move it in the tests and made a testComponent in the spec file.
```
@Component({ template: `
    <my-app>
        <hello>
        </hello>
    </my-app>
` })
class TestComponent {}
```
It seems like it might be when projection is involved that the problem arises?


Here is the modified one, i added a new spec file as well that is identical with removed MockComponent and those tests work.
https://stackblitz.com/edit/bah-imogy4?embed=1&file=app/hello.component.spec.ts

**Comment by kenborge** [comment]
@getsaf Creating a TestComponent does have some pretty valid use cases. Like if you want to test projected content. So you need to compile something like:
```
@Component({ template: `
    <hello>
      PROJECTED CONTENT
    </hello>
` })
class TestComponent {}
```

It does seem like this is possible with the viewProviders approach though. It doesn't work using normal provide but overriding viewProviders seems to be a solution.  
https://stackblitz.com/edit/bah-yfg6d8?embed=1&file=app/hello.component.spec.ts

**Comment by ike18t** [comment]
@kenborge Did that solve your problem?  Is it cool if I close this issue?

**Comment by ike18t** [comment]
Closing unless there is a reason not to.  Feel free to reopen if this is still an issue.
