### ISSUE TITLE
RFC: Exploration of use-cases for Angular JIT compilation mode

### ISSUE THREAD

**Issue by SerkanSipahi** [ike18t/ng-mocks#1006]
@satanTime Maybe this is interesting for you because it will affect the test as well.

### **The introduction from the Angular team on this topic:**

The Angular team would like to understand the remaining use-cases for Angular's JIT compilation mode, and discover any gaps that prevent adoption of the AOT compilation mode for these use-cases.

You would like the community, to share with Angular-Team how and why you still use JIT mode, and what prevents you from using AOT.

See also: 
- https://github.com/angular/angular/issues/43133 
- https://github.com/angular/angular/issues/43133#issuecomment-898477405
> ...you are right that the **testing components** today rely on JIT. Usually not because they are dynamic but because you need the flexibility to declare them inline, usually within functions of a test file as your example shows.

**Comment by satanTime** [comment]
Hi @SerkanSipahi,

thanks for the info. it looks like we are fine here based on their conclusion.
I'll add support for `.ɵ*` once Angular runs tests in AOT out of the box, but considering the trend that everybody uses `jest` for angular now, and `jest` development is so slow that I cannot imagine how long it will take to migrate everything there.
