### ISSUE TITLE
False positive ng-mocks not in JIT

### ISSUE THREAD

**Issue by scowling** [ike18t/ng-mocks#1036]
AngularFirestore declaration has been passed into ng-mocks without Angular decorators

Error message sent me here.. what more information do you require?

**Comment by satanTime** [comment]
Hi there. 

Usually it means, there is something, a class, which wasn't decorated. Usually it's caused by a wrong import or if jest mocks an import. 

Could you provide more info about your setup? Or a min repo would be great.

**Comment by satanTime** [comment]
Also could you confirm that you are using the latest version of `ng-mocks`?

**Comment by scowling** [comment]
I was using the latest version; however I'll close this issue as I changed the way I am using ng-mocks and it is working so far.
Thanks for this module, keep up the great work

**Comment by satanTime** [comment]
That's great, thanks for feedback!
