### ISSUE TITLE
Documentation / Example for MockService

### ISSUE THREAD

**Issue by omnibrain** [ike18t/ng-mocks#108]
I'm trying to figure out how to use `MockService` but I don't get it. An example would be very helpful, as done for the other mocking functions. 

Very useful library BTW! Shame Angular doesn't provide something like that out of the box.

**Comment by satanTime** [comment]
Hi,

at current point `MockService` is more internal thing and used in `MockModule` to mock providers.
Although you can use it too, simply pass into it a class or an object. result will be a mocked instance that has the same methods as the passed class, or an object that has function as original one. All properties / keys that aren't functions will be omitted.
The purpose of the `MockService` is to get rid of any logic from a class but to keep the same methods that don't do anything and can be spied.

**Comment by omnibrain** [comment]
Ok, that makes sense, thanks a lot for the explanation! I'm closing this issue. 

The auto mock feature looks awesome, that's exactly what I was hoping for. Any idea if / when this will be merged?

**Comment by satanTime** [comment]
I think it will be released this or next weekend. You can subscribe to the notifications in the top bar "Watch - Releases Only"
