### ISSUE TITLE
Rendering mocked component ContentChildren broken after upgrade to ng9

### ISSUE THREAD

**Issue by twjacobsen** [ike18t/ng-mocks#109]
I have a number of component tests in my project, that rely on mocking dependant components. Many of them also rely on rendering outlets in these mocked components.

Before upgrading to ng9, everything worked just fine. But now, the outlets aren't rendered anymore. I've tried debugging, and I've found that in this line https://github.com/ike18t/ng-mocks/blob/master/lib/mock-component/mock-component.ts#L118 the `viewContainer` is always undefined.

If I explicitly disable Ivy (`"angularCompilerOptions": { "enableIvy": false }` in tsconfig.spec.ts), tests pass. The problem is, I can't easily do this for all my libs.

Have you tried unit testing with Ivy enabled? I don't see it being disabled in your tsconfig

**Comment by satanTime** [comment]
Hi @twjacobsen, thanks for the report. Might you share `@ContentChild`, `@ContentChildren`  you have in the failing component? I'll try to reproduce it locally.

**Comment by twjacobsen** [comment]
Here's the source of the component I mock (template and ts):

```html

<!--
    Using cdkVirtualScroll here introduces some very odd behaviour.
    Keep an eye on https://github.com/angular/material2/issues/10122, where a list of other cdk features that need drag-drop integration is maintained.
-->
<div cdkDropList (cdkDropListDropped)="onDrop($event)">
    <!-- Use inline markup here, since cdkDropList and cdkDrag don't work too good when present in different components. Having cdkDragHandle as a non- -->
    <div
        class="drag-drop-list-item"
        [style.minHeight.px]="itemHeight"
        [style.paddingTop.px]="index !== 0 ? itemSpacing : 0"
        cdkDrag
        [cdkDragDisabled]="!enableDragDrop || !enableItemDragDrop(item)"
        *ngFor="let item of (filteredItems$ | async); let index = index"
        [ngClass]="{ active: compareItemsBy(item, selectedItem) }"
    >
        <div class="controls">
            <div class="additional-control" *ngIf="additionalControl">
                <ng-container *ngTemplateOutlet="additionalControl; context: { $implicit: item }"></ng-container>
            </div>
            <mat-icon
                cdkDragHandle
                [cdkDragHandleDisabled]="isFilterActive"
                [ngClass]="{ disabled: isFilterActive }"
                *ngIf="enableDragDrop && enableItemDragDrop(item)"
                >{{ dragIcon }}</mat-icon
            >
        </div>
        <ng-container *ngTemplateOutlet="dragDropListItemTmpl; context: { $implicit: item, index: index }"></ng-container>
    </div>
</div>
```
```ts
...
@Component({
    selector: 'lp-drag-drop-list',
    templateUrl: './drag-drop-list.component.html',
    styleUrls: ['./drag-drop-list.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class DragDropListComponent<T> {
    ...
    @ContentChild('dragDropListItem') dragDropListItemTmpl!: TemplateRef<ElementRef>;
    @ContentChild('additionalControl') additionalControl!: TemplateRef<ElementRef>;
    ....
}
```

**Comment by satanTime** [comment]
Awesome! Thanks! I'll check next days.

**Comment by satanTime** [comment]
I was able to reproduce the issue, working on fix.

**Comment by satanTime** [comment]
Hi @twjacobsen, could you verify the fix?
you need to download: https://github.com/satanTime/ng-mocks/archive/issues/109.zip
```bash
npm install
npm run build
```
you should get `dist` directory. Simply  replace `node_module/ng-mocks/dist` with it and execute `npm run test` in your project.

**Comment by twjacobsen** [comment]
Thanks, I'll verify if I get time this weekend, otherwise I'll check it Monday 👍

**Comment by twjacobsen** [comment]
On first sight, it looks very promising. I still have a few failing tests, but I'll have to verify if they're related to ng-mocks or some other Ivy related change - I'll do this monday :)

**Comment by twjacobsen** [comment]
@satanTime My co-worker has just verified, that your fix is working as it should 👍 Sorry for the delay!

**Comment by satanTime** [comment]
Ha, I was writing a test with mock of ContentChild in a new angular9 project and got the issue too.

**Comment by satanTime** [comment]
Hi @ike18t, let's release a new version this weekend if you don't mind. I need this fix for beta version.

**Comment by satanTime** [comment]
Hi @twjacobsen, 9.3.0 has been released, please let me know if you meet any issues.

**Comment by twjacobsen** [comment]
We will install the updated version later next week and let you know about the results

**Comment by twjacobsen** [comment]
@satanTime I finally got around to upgrading last night, and most of our tests are running now - but some, that used to run are now broken.

From what I can tell, decorated methods are omitted from the mocked component...does that make sense to you?

Specifically, I have a test that is creating a spy on a method from a mocked component, but it fails because the method is not found. I've compared the properties of the mocked object with the properties of the actual class, and only my decorated methods are missing. So are you somehow filtering out methods with other decorators than input and output?

**Comment by satanTime** [comment]
@twjacobsen, thanks for the update, a very interesting turn :) 

Might you share how you decorate the missed methods?

Recently we added code that mocks all methods, but I guess it was in the code base when you met the issue: https://github.com/ike18t/ng-mocks/commit/b119547292312ffb5d4bf87d839195da78bcb8aa

Also as an option you can try auto spy: https://github.com/ike18t/ng-mocks#auto-spy
And then to use `mockService` https://github.com/ike18t/ng-mocks#mockhelper

Perhaps it will help, but anyway I would like to understand why the decorated methods were skipped. I know that properties can be skipped, because they aren't detected by `Object.getOwnProperties`, but methods don't have issues usually.

Anyway would be great if you could share code with me, maybe invite me to a repo with a single file with the decorator.

**Comment by twjacobsen** [comment]
I've just re-run the tests on `ng-mocks@10.0.0-alpha.5` and the error is the same.

The methods in question simply have the `@Memoize` decorator from `lodash-decorators@4.5.0` - nothing fancy.

Also, using auto-spy does not work either - the method is still not defined on the mock object.

One (maybe important) detail is, that the mocked component is referenced in the tested component from `@ViewChild` - something like this:

```
// tested-component.ts
@Component({})
class TestedComponent {
  @ViewChild(MockedComponent) mockedComponent: MockedComponent;
}

// mocked-component.ts
@Component({})
class MockedComponent {
  @Memoize()
  someMethod(): void {}
}

// tested-component.spec.ts
spyOn(testedComponent.mockedComponent, 'someMethod').and.callFake(() => '')
```

**Comment by satanTime** [comment]
Thanks! I'll check next days. Might you confirm `TestBed`?

```typescript
TestBed.configureTestingModule({
  declares: [TestedComponent, MockComponent(MockedComponent)],
})
```

**Comment by twjacobsen** [comment]
Yup, that's how it's set up.

**Comment by satanTime** [comment]
Aha, I was able to reproduce the issue. Working on the fix.

**Comment by twjacobsen** [comment]
Ah, but AFAIK that's pretty common for decorators to do, right? I hope you can figure something out - I'm pretty much a novice when it comes to how angular components work under the hood, otherwise I'd love to help out

**Comment by satanTime** [comment]
I found a way, finalising changes.

**Comment by satanTime** [comment]
Hi @twjacobsen, might you verify that changes in https://github.com/satanTime/ng-mocks/tree/issues/109 work for you?

That's the test I've used
```typescript
import {Component, NgModule, ViewChild} from '@angular/core';
import {TestBed} from '@angular/core/testing';
import {Memoize} from 'lodash-decorators';
import {MockComponent, MockHelper} from 'ng-mocks';

@Component({
    selector: 'mocked',
    template: 'hello',
})
class MockedComponent {
    @Memoize()
    someMethod(): void {}
}

@Component({
    selector: 'test',
    template: '<mocked></mocked>'
})
class TestedComponent {
    @ViewChild(MockedComponent) mockedComponent: MockedComponent;
}

@NgModule({
    declarations: [
        TestedComponent,
        MockedComponent,
    ]
})
class TestModule {
}

describe('TestModule', () => {
    beforeEach(() => {
        return TestBed.configureTestingModule({
            declarations: [
                TestedComponent,
                MockComponent(MockedComponent),
            ],
        }).compileComponents();
    });

    fit('TestedComponent', () => {
        const fixture = TestBed.createComponent(TestedComponent);
        fixture.detectChanges();
        const testedComponent = fixture.componentInstance;
        MockHelper.mockService(testedComponent.mockedComponent, 'someMethod');
        spyOn(testedComponent.mockedComponent, 'someMethod').and.callFake(() => '');
        expect(testedComponent.mockedComponent.someMethod() as any).toBe('');

        MockHelper.mockService(testedComponent.mockedComponent, 'someMethod1', 'get');
        MockHelper.mockService(testedComponent.mockedComponent, 'someMethod1', 'set');
        (testedComponent.mockedComponent as any).someMethod1 = '5';
        expect((testedComponent.mockedComponent as any).someMethod1).toBe('5');
    });
});
```

**Comment by twjacobsen** [comment]
Yes, using your branch works, if I also use `MockHelper` before creating the spy. 👍

**Comment by satanTime** [comment]
Awesome, I'll release a new version on Sunday.

**Comment by satanTime** [comment]
Hi @twjacobsen, 9.4.0 has been published. Please let me know how it works for you and happy coding!
