### ISSUE TITLE
MockBuilder.mock() does not override previously mocked mocks with InstanceMock

### ISSUE THREAD

**Issue by krema** [ike18t/ng-mocks#1110]
hi, I think I propaply found a bug. 

I try to mock the same InjectionToken in two different tests but with different data. 

`test-one (working test)`
```
  MockBuilder(TargetComponent, TargetModule).mock(TOKEN, { hello: '1' })

  it('1', () => {
    const fixture = MockRender(TargetComponent);
    const component = fixture.point.componentInstance;
    expect(component.data).toEqual('1');
  });

  it('2', () => {
    MockInstance(TOKEN, () => ({
      hello: '2',
    }));
    const fixture = MockRender(TargetComponent);
    const component = fixture.point.componentInstance;
    expect(component.data).toEqual('2');
  });
```

`test-two (failing test)`
```
  MockBuilder(TargetComponent, TargetModule).mock(TOKEN, { hello: 'failing-hello' })

  it('3', () => {
    const fixture = MockRender(TargetComponent);
    const component = fixture.point.componentInstance;
    expect(component.data).toEqual('failing-hello');
  });
```
**test-two** is failing because it got the mocked data from the previous test **test-one**. 

> Error: Expected '2' to equal 'failing-hello'.

I prepared also a stack blitz to demonstrate this. 

https://stackblitz.com/edit/github-cnkgma?file=src%2Ftests%2Fa-my-issue%2Ftest.spec.ts

Is that working as expected or is that a bug? Maybe I misused the framework? I would expect that MockBuilder.mock() calls MockReset every time for that specific InjectionToken.

**Comment by GerkinDev** [comment]
Hi,

I guess ng-mocks caches mocks for some reason (speed ? avoid re-check & re-generate already mocked tokens ?), so I'm not sure this is a bug.

If you call `ngMocks.reset()` before your `MockBuilder` call, it works: https://stackblitz.com/edit/github-cnkgma-wxjiwt?file=src%2Ftests%2Fa-my-issue%2Ftest.spec.ts
See https://ng-mocks.sudo.eu/api/ngMocks/reset

**Comment by satanTime** [comment]
Hi all,

Thanks for the info. I'll take a look the next week. 

For now I would say MockBuilder should be inside beforeEach, and beforeEach should return its result.

**Comment by satanTime** [comment]
Yep. You are right, this is a bug. Between tests the reset should be performed automatically.

**Comment by satanTime** [comment]
Oki. Sorry for the confusion. I took a look deeper, and yes, @GerkinDev is right.

When `MockInstance` is used, there should be its reset back.
There are 2 ways to do it:
- reset manually in afterEach / afterAll: https://ng-mocks.sudo.eu/api/MockInstance#resetting-customization
- configure auto reset: https://ng-mocks.sudo.eu/extra/install#default-customizations


Please keep the issue open, I'll update docs to highlight this requirement.
- https://ng-mocks.sudo.eu/api/MockInstance#resetting-customization
- https://ng-mocks.sudo.eu/extra/install#default-customizations

**Comment by krema** [comment]
@satanTime 
Thanks for checking. In my example, if you check the `test.ts` file, we have configured the automatic reset. It seems to be a bug that it doesn't reset between test-suites.

https://stackblitz.com/edit/github-cnkgma?file=src%2Ftest.ts 
```
jasmine.getEnv().addReporter({
  specDone: MockInstance.restore,
  specStarted: MockInstance.remember,
  suiteDone: MockInstance.restore,
  suiteStarted: MockInstance.remember,
});

```

**Comment by satanTime** [comment]
Ah. Sorry. Missed that part. Then you are right. It should do the magic. I'll take a look the next weeks.

**Comment by satanTime** [comment]
Hi @krema, 

could you try with `13.1.0`? I added changes in `MockInstance`, maybe it has fixed your issue.

**Comment by satanTime** [comment]
I'm going to close the issue. Feel free to reopen it if it doesn't work.
