### ISSUE TITLE
@Untildestroy decorators breaks the mock component

### ISSUE THREAD

**Issue by sheikalthaf** [ike18t/ng-mocks#117]
Hi,

I'm using the [@ngneat/until-destroy](https://github.com/ngneat/until-destroy) library. If i try to mock the component. Then I'm getting error like `TypeError: Cannot read property 'get' of undefined`. How to solve this?

Thanks for this awesome library

**Comment by satanTime** [comment]
Hi @sheikalthaf,

thanks for the report, might you provide a simple example how a component and a test that reproduce the issue?

I'll take a look later this week.

**Comment by satanTime** [comment]
I wasn't able to reproduce the issue:

`app.component.ts`
```typescript
import {Component, OnInit} from '@angular/core';
import {UntilDestroy, untilDestroyed} from '@ngneat/until-destroy';
import {interval} from 'rxjs';

@UntilDestroy()
@Component({
    selector: 'app-test',
    template: '{{ value }}',
})
export class AppTestComponent implements OnInit {
    public value: number;

    ngOnInit() {
        interval(500).pipe(
            untilDestroyed(this),
        ).subscribe(value => {
            console.log(value);
            this.value = value;
        }, console.error, () => console.log('completed'));
    }
}

@UntilDestroy()
@Component({
    selector: 'app-root',
    template: '<app-test *ngIf="show"></app-test>',
})
export class AppComponent implements OnInit {
    public show: boolean = true;

    ngOnInit() {
        interval(5000).pipe(
            untilDestroyed(this),
        ).subscribe(value => this.show = value % 2 > 0);
    }
}
```

and its test `app.component.spec.ts`
```
import {TestBed} from '@angular/core/testing';
import {MockComponent, MockHelper, MockRender} from 'ng-mocks';

import {AppComponent, AppTestComponent} from './app.component';

describe('app', () => {
    beforeEach(async () => {
        await TestBed.configureTestingModule({
            declarations: [
                MockComponent(AppTestComponent),
                AppComponent,
            ],
        }).compileComponents();

        jasmine.clock().install();
    })

    afterEach(() => {
        jasmine.clock().uninstall();
    })

    it('test', () => {

        const fixture = MockRender(AppComponent);

        const check1 = MockHelper.find(fixture.debugElement, AppTestComponent);
        expect(check1).not.toBeNull();

        jasmine.clock().tick(5000);
        fixture.detectChanges();
        const check2 = MockHelper.find(fixture.debugElement, AppTestComponent);
        expect(check2).toBeNull();
    });
});
```

`app.module.ts`
```typescript
import {HttpClientModule} from '@angular/common/http';
import {NgModule} from '@angular/core';
import {BrowserModule} from '@angular/platform-browser';

import {AppComponent, AppTestComponent} from './app.component';

@NgModule({
    declarations: [AppComponent, AppTestComponent],
    imports: [
        BrowserModule,
        HttpClientModule,
    ],
    bootstrap: [AppComponent],
})
export class AppModule {}
```

**Comment by sheikalthaf** [comment]
@satanTime Thanks for detailed response. I'm using `jest` for testing and also I'm using `MockComponents`. Maybe it is the problem?

**Comment by satanTime** [comment]
I see, might you provide an example how to reproduce the issue? Stackbiz or a zip archive.

**Comment by sheikalthaf** [comment]
@satanTime will create a repo and share with you.

**Comment by satanTime** [comment]
Hi @sheikalthaf, I think something similar was discovered in issue #109 with other decorators. Might you update to 9.4.0 and verify if the issue is still here?

I assume that `.get` comes from a property of a component, before 9.4.0 ng-mocks  was ignoring mocking of properties, now it mocks them.

There is more info about that [MockHelper.mockService](https://github.com/ike18t/ng-mocks#mockhelper).

Any feedback is welcome, happy coding!

**Comment by sheikalthaf** [comment]
I solved this problem by running my test with ivy enabled. Still I will give it a try with latest version.

Thanks for this library which reduce my lots of boiler plate code in testcases

**Comment by satanTime** [comment]
Aha, ivy - that's nice :) then definitely please give a try 9.4.0, quite sure it won't have the issue. If it does I would like to ask you to find some time some day and create an example of the issue. Perhaps it's possible to invite me to the repo for the investigation.
