### ISSUE TITLE
[Bug] No Directive annotation found on e

### ISSUE THREAD

**Issue by norato** [ike18t/ng-mocks#133]
This error occurs when I export some methods from ng-mocks beside other application files.

```console.error
Uncaught Error: No Directive annotation found on e
```

Steps to reproduce:

Create an `index.ts` file exporting some services or components and exports in the same file any component mock

Example:
```ts
export * from './foobar.service';
export * from './component/any.component';

export const SomeComponentMock = MockComponent(SomerComponent);
export const SomeDirectiveMock = MockDirective(SomeDirective);
export const SomePipeMock = MockPipe(SomePipe);
```

We are using: 
```json
{
  "dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^9.2.3",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/flex-layout": "9.0.0-beta.29",
    "@angular/forms": "~9.1.0",
    "@angular/material": "^9.2.3",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0"
 },
 "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular-devkit/core": "9.1.7",
    "@angular-devkit/schematics-cli": "^0.901.7",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "ng-mocks": "^9.2.0",
  }
} 
```

**Comment by satanTime** [comment]
Hi @norato,

thank you for the report.

Might you add also an example how you import it and how you run the app to get the error?

**Comment by norato** [comment]
Hey @satanTime, 

Following the steps to reproduce it will rise the error, but missing one thing.

This does not raise errors on ng server, but on serving the production build.
That index file needs to be used in any part of the application.

So you can import that exported service in the AppComponent from the index file.

Run the production build
And serve the dist files using lite-server, for example

**Comment by satanTime** [comment]
Just my curiosity, what is the reason to include `ng-mocks` in production build?

**Comment by norato** [comment]
I did not include that for real... this was really a side effect.
That was just because I exported it in the index.ts from a utils folder in the shared module.

Just to make that imports easy

**Comment by satanTime** [comment]
Works for me without any issue: [ng-mocks-a9.zip](https://github.com/ike18t/ng-mocks/files/4696662/ng-mocks-a9.zip)

**Comment by norato** [comment]
@satanTime it works, you do not import the index.ts anywhere.

Here, I import a fake service from index.ts inside app.component and it fails.
[ng-mocks-a9 2.zip failing](https://github.com/ike18t/ng-mocks/files/4697642/ng-mocks-a9.2.zip)

![image](https://user-images.githubusercontent.com/395588/83181666-97120f00-a0fb-11ea-9b6e-235b4c653b7f.png)


![image](https://user-images.githubusercontent.com/395588/83181588-7f3a8b00-a0fb-11ea-8c5e-c3f4c6a31874.png)

**Comment by satanTime** [comment]
It's imported in the app module: https://take.ms/C2Wwg

**Comment by satanTime** [comment]
After some time I would say there's no an easy way to provide mocks without testing env, the errors comes exactly because of missed test env.

Would it be expected for you if it failed with a more readable exception asking to remove ng-mocks from production build?

**Comment by satanTime** [comment]
Please check 9.5.0, it provides a readable error now.
