### ISSUE TITLE
Bug: Does it work in an Angular project with libraries

### ISSUE THREAD

**Issue by appienvanveen** [ike18t/ng-mocks#139]
Hi,

I'm figuring out this library, since I really like the idea to provide the mocks of your component in stead of just acceptating everything.

Currently I'm trying to mock a component in an Angular application with a angular library. Like this

projects
 --- app1    
      --- componentX which uses ComponentY <-- i don't get this test working
--- lib1
 -------ComponentY

I got an error like this:

resolve '/lib/forms/j.pipe' in 'x:\xxx\xxx.git\xxx-xx\xx\xx-xxx\src\app\xx\xx-view'
  Parsed request is a module
  using description file: Dxxx\x\xxx.xxx\xxxx-web\package.json (relative path: ./xxx/xxx-xxx/src/app/xxx/xxx-view)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: x:\xx\\xxx-x\package.json (relative path: ./x/x-x/src/app/x/x-view)
      Field 'browser' doesn't contain a valid alias configuration
      using description file: x:\x\xxx\x-x\dist\xxx-xxx\package.json (relative path: ./lib/x/xxxxxx)
        no extension
          Field 'browser' doesn't contain a valid alias configuration

Is this setup already tried before? 

If requested, I can provide a example project

**Comment by satanTime** [comment]
Hi,

thank you for the report. Might you share how the test, the componentX's class and its template look like too?

**Comment by satanTime** [comment]
Hi @appienvanveen, I hope this finds you well, do you have any update on my previous comment?

**Comment by appienvanveen** [comment]
I will try to reproduce it tomorrow. I tried Friday but then it worked
somehow

Op zo 14 jun. 2020 11:53 schreef MG. <notifications@github.com>:

**Comment by appienvanveen** [comment]
I've tried it again and it works now. Dunno what exactly was wrong; probably my mind was already weekend :)

**Comment by satanTime** [comment]
Ah, awesome :)
