### ISSUE TITLE
Incorrect examples?

### ISSUE THREAD

**Issue by kennethversaw** [ike18t/ng-mocks#140]
I am currently using ng-mocks version 9.5.0 and it seems as if your examples are incorrect. When I attempt to import ngMocks or MockBuilder I get an "ng-mocks has no exported member 'MockBuilder'" and "ng-mocks has no exported member 'ngMocks'". Have these imports changed and the documentation not been updated? 

![image](https://user-images.githubusercontent.com/4662609/84550235-aaae9f80-accf-11ea-8a24-f22883b63d36.png)

**Comment by satanTime** [comment]
Hi, you are right, this version will be released on Sunday, current API is present on NPM https://www.npmjs.com/package/ng-mocks, it doesn't include `MockBuilder`.

**Comment by kennethversaw** [comment]
Thanks for the reply! That example still seems to include ngMocks which is also not exported. Is that also coming in the Sunday release?

**Comment by satanTime** [comment]
It should be present in 9.5.0 already, I'll double check it tomorrow and it will be fixed in the release on Sunday.

**Comment by satanTime** [comment]
I've tried with 9.5.0 on angular 9 and was able to import and use `ngMocks `. Perhaps the version you have is older.

**Comment by satanTime** [comment]
Hi there, 9.6.0 has been released. I'm going to close the issue, feel free to reopen it if something doesn't work for you.
