### ISSUE TITLE
Error: More than one custom value accessor matches form control with unspecified name attribute

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#145]
Hello @ike18t,
With ng-mocks 9.6, I have an error in _@angular/forms_ when I use **ReactiveFormsModule** and _@angular/material_ **mat-input** directive with **cdkTextareaAutosize** directive in a html **text-area** tag.
You can see the error in [Stackblitz](https://stackblitz.com/edit/angular-ngmocks-form-error).
The code works fine in production.
Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi @cdupetit,

thanks for the report, I'll take a look tonight.

**Comment by cdupetit** [comment]
The same error can be reproduced with **mat-input** and **matAutocomplete**.

**Comment by satanTime** [comment]
was it working correctly on 9.5.0?

**Comment by cdupetit** [comment]
> was it working correctly on 9.5.0?

Yes

**Comment by satanTime** [comment]
Thanks,

that's how it works for me at the moment, nevertheless fixing the issue.
```typescript
import {ComponentFixture, TestBed} from '@angular/core/testing';
import {MockBuilder} from 'ng-mocks';

import {AppModule} from '../app.module';

import {InputTextareaFormComponent} from './input-textarea-form.component';

describe('Testing tests', () => {
  let component: InputTextareaFormComponent;
  let fixture: ComponentFixture<InputTextareaFormComponent>;

  beforeEach(() => MockBuilder(InputTextareaFormComponent, AppModule));

  beforeEach(() => {
      fixture = TestBed.createComponent(InputTextareaFormComponent);
      component = fixture.componentInstance;
  });

  it('should succeed', () => {
    expect(true).toEqual(true);
  });
});
```

**Comment by cdupetit** [comment]
Thank you very much.

**Comment by satanTime** [comment]
Hi again,

Might you verify the fix? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4814833/ng-mocks.zip)
simply replace `ng-mocks` in `node_modules` with its content.

`MockBuilder` is a new feature that facilitates configuration of the TestBed and has many improvements under the hood compare to direct usage of `Mock*` functions.

Starting 9.6.0 I would say that `MockBuilder` should be used everywhere except situations when you need an exotic behavior that it doesn't provide, but I can hardly imagine this case.

**Comment by cdupetit** [comment]
Hi,
Sorry for the wait. You fixed the bug.
Thank you very much for your quick response.

**Comment by satanTime** [comment]
Great, thanks for the feedback, I'll release the update later this week.

**Comment by satanTime** [comment]
Hi again, 9.6.3 has been released, please let me know how it works for you.

**Comment by cdupetit** [comment]
The version 9.6.3 fix the bug.
Thank you very much.
