### ISSUE TITLE
MockBuilder: Testing HttpInterceptor in conjunction of HttpClientInMemoryWebApiModule replace HttpClientTestingBackend by HttpBackend

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#147]
Hello @ike18t,
I use MockBuilder with ng-mocks 9.6.3.
When I try to test an **HttpInterceptor** in conjunction with a **HttpClientInMemoryWebApiModule**, the second one is not correctly mocked. The **HttpClientTestingBackend** is replaced by **HttpBackend** (see the second test in StackBlitz).
I don't know how to remove **HttpClientInMemoryWebApiModule** from test or how to mock correctly **HttpClientInMemoryWebApiModule**.
You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-http-interceptor-in-memory-web-api).
The code works fine in production.
Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi again. 

Thanks for the report. I’ll take a look at the beginning of the next week. 

Do you use .replace with testing for the http module?

**Comment by satanTime** [comment]
Aha. I see. Great. Once I’m back to work I’ll check it as the first thing.

**Comment by satanTime** [comment]
After investigation I found that because you want to use `HttpClientTestingModule` and `RouterTestingModule` you need to keep the original modules too, then it works as expected:

```typescript
      MockBuilder(HttpErrorInterceptor, AppModule)
          .keep(HttpClientModule)
          .keep(RouterModule)
          .keep(HttpClientTestingModule)
          .keep(RouterTestingModule)
          .provide({provide: HTTP_INTERCEPTORS, useClass: HttpErrorInterceptor, multi: true})
          .provide({ provide: RETRY_ATTEMPTS, useValue: maxRetryAttempts })
          .provide({ provide: SCALING_DURATION, useValue: scalingDuration })
```
