### ISSUE TITLE
Mockbuilder: looking for a special example. (this is not an issue)

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#150]
Hi again,
It's not an issue but I'm looking for an equivalent to :
```
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [
        MyModule.forRoot()
      ]
    });
  });
```
with MockBuilder.
My purpose is to test the module **MyModule**.
Thank you in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi there,

depends what you want to achieve. If you want to test how `MyModule.forRoot()` works - then you don't need neither TestBed nor MockBuilder.

If you want to mock / keep it in an imported module you can use `.keep` or `.mock`, it affects providers too.

```typescript
@NgModule({
    imports: [
        HttpClientInMemoryWebApiModule.forRoot(),
    ],
})
export class AppModule {}

MockBuilder(Something, AppModule)
  .keep(HttpClientInMemoryWebApiModule) // won't mock the module and all providers
  .mock(HttpClientInMemoryWebApiModule) // will mock the module and all providers
;
```
