### ISSUE TITLE
False positive ng-mocks not in JIT ( declaration has been passed into ng-mocks without Angular decorators)

### ISSUE THREAD

**Issue by dean-g** [ike18t/ng-mocks#1506]
I am getting the following error while upgrading my angular package, 

DialogModule declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely, jest.mock() has been used on its file, or ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.

Can someone please please me with this? 

```
 at ../../../../../libs/ng-mocks/src/lib/common/error.missing-decorators.ts:4:9
      at Object.<anonymous>.exports.default (../../../../../libs/ng-mocks/src/lib/common/core.reflect.body-catch.ts:12:27)
      at ../../../../../libs/ng-mocks/src/lib/common/core.reflect.module-resolve.ts:9:108
      at getMockModuleDef (../../../../../libs/ng-mocks/src/lib/mock-module/mock-module.ts:101:42)
      at detectMockModule (../../../../../libs/ng-mocks/src/lib/mock-module/mock-module.ts:112:25)
      at MockModule (../../../../../libs/ng-mocks/src/lib/mock-module/mock-module.ts:175:22)
```

**Comment by cedbesafilm** [comment]
see #1427

**Comment by satanTime** [comment]
Hi @dean-g, might you check whether your case belongs to https://github.com/ike18t/ng-mocks/issues/1427?

**Comment by satanTime** [comment]
I'm closing this ticket. It should be fixed by https://github.com/ike18t/ng-mocks/issues/1427. 

Feel free to Re-open it if you still encounter the issue.

**Comment by satanTime** [comment]
[v13.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by patelvimal** [comment]
thanks @satanTime for all the efforts.
