### ISSUE TITLE
MockBuilder: Testing a Router Resolve Service declared in a lazy loading module

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#152]
Hi @satanTime,
When I use `MockBuilder` to test a Router Resolve Service declared in a lazy loading module.
I get this error :

`Error: Component XXXComponent is not part of any NgModule or the module has not been imported into your module`

I've tried to use  `RouterTestingModule.withRoutes`, without success.
You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-resolver).
The code works fine in production.

> _angular.json_
> **Production :**
> projects -> demo -> architect -> build -> options -> main -> src/main.ts
> **Testing :**
> projects -> demo -> architect -> build -> options -> main -> src/main-testing.ts

Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi again, might you explain the purpose of `.replace(RouterModule, RouterTestingModule)` in your test?

**Comment by cdupetit** [comment]
Hi again,
I use a router in the resolver to redirect the user in case of not found value.
Best Regards.
Cyril

**Comment by satanTime** [comment]
I see, but do you need for that RouterModule, RouterTestingModule? I think it's enough to check that it was imported and called.

Might you add a test to StackBlitz without ng-mocks and with RouterTestingModule?
It should help me with better understanding of your case.

**Comment by cdupetit** [comment]
Done on same [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-resolver).

**Comment by satanTime** [comment]
Thanks, I'll take a look this evening.

**Comment by satanTime** [comment]
Based on the provided code MockBuilder should be used like that:

```typescript
    beforeEach(() => MockBuilder()
        .keep(RouterTestingModule)
        .mock(ActivatedRouteSnapshot, {})
        .mock(RouterStateSnapshot, {})
    );
```

**Comment by cdupetit** [comment]
Thank you very much.
