### ISSUE TITLE
Compatibilty with Angular 10

### ISSUE THREAD

**Issue by aishwaryasharma14** [ike18t/ng-mocks#155]
Hi @satanTime @askarby 

After upgrading to Angular 10, the unit tests are failing with error - `ERROR in node_modules/ng-mocks/dist/lib/common/lib.d.ts:12:57 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).`

After making the below change on that line, it works fine -
`export interface NgModuleWithProviders<T = any> extends ModuleWithProviders<T> {}`

Are we planning to make it compatible with Angular 10 anytime soon?

**Comment by satanTime** [comment]
Thanks for the report, it's already in the issue list #148
