### ISSUE TITLE
Error: FooBarDirective declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled

### ISSUE THREAD

**Issue by stefan-niedermann** [ike18t/ng-mocks#1595]
## Using:
- `angular@13.1.2`
- `ng-mocks@13.0.0-alpha.2`

I am not sure which kind of Angular decorators are meant. The `FooBarDirective` is decorated with `@Directive` (with a corresponding selector). The only "special" thing here is, that the selector of this directive matches a native HTML attribute.

## Last known combination that worked:
- `angular@13.0.2`
- `ng-mocks@^12.5.0`

## Console output:

```
Error: FooBarDirective declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely,  ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.
    at node_modules/ng-mocks/cjs/lib/common/error.missing-decorators.js:5:1
    at node_modules/ng-mocks/cjs/lib/common/core.reflect.body-catch.js:16:1
    at node_modules/ng-mocks/cjs/lib/common/core.reflect.directive-resolve.js:18:6
    at node_modules/ng-mocks/cjs/lib/common/core.reflect.meta.js:14:1
    at generateTouches (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:136:1)
    at generateTouches (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:138:1)
    at defineTouches (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:169:1)
    at Function.<anonymous> (node_modules/ng-mocks/cjs/lib/common/ng-mocks-global-overrides.js:257:1)
    at Function.<anonymous> (node_modules/ng-mocks/cjs/lib/mock-helper/mock-helper.faster-install.js:43:1)
    at UserContext.<anonymous> (libs/aaa/feature-bbb/src/lib/ccc/ddd.component.spec.ts:44:9)
```

**Comment by satanTime** [comment]
Hi, thanks for the report. Might you share how the decoration looks like?

**Comment by stefan-niedermann** [comment]
```typescript
@Directive({
    selector: 'a[href]:not([data-foo-bar])'
})
```

**Comment by stefan-niedermann** [comment]
That's why i am testing `ng-mocks@13.0.0-alpha.2` which [is supposed to be compatible again](https://github.com/ike18t/ng-mocks/issues/1427#issuecomment-1008362550).

**Comment by LukasMachetanz** [comment]
Ah okay; sorry for that. 😬

**Comment by satanTime** [comment]
Hi @stefan-niedermann, could you try latest alpha?

**Comment by stefan-niedermann** [comment]
Thank you very much for the quick reaction! Version `13.0.0-alpha.5` fixed this issue. I still have some other problems, but since I am not sure whether they are related to `ng-mocks`, I'll close this issue.

**Comment by satanTime** [comment]
Hi @stefan-niedermann 

thanks for the confirmation.

Feel free to post the left issues in the main issue for A13. Maybe they'll resonate to other devs.
