### ISSUE TITLE
Use NO_ERRORS_SCHEMA with mockbuilder

### ISSUE THREAD

**Issue by Tallyb** [ike18t/ng-mocks#1642]
Is there a way to add the NO_ERRORS_SCHEMA when using mockbuilder and not TestBed?

**Comment by satanTime** [comment]
Hi @Tallyb,

I think it should be possible to do via `.beforeCompileComponents`:

```ts
beforeEach(() => MockBuilder().beforeCompileComponents(testBed => testBed.configureTestingModule({
  schemas: [NO_ERRORS_SCHEMA],
})));
```

**Comment by Tallyb** [comment]
I am afraid the beforeCompileComponents is not really documented....

**Comment by satanTime** [comment]
Yep, it's available, but wasn't documented yet.
