### ISSUE TITLE
MockComponent ViewChild Service

### ISSUE THREAD

**Issue by RobertasM** [ike18t/ng-mocks#170]
Is there possibility to mock ViewChild component injected services? Currently my parent component has ViewChild component and it tries to call exposed public service method of this child component. Now it fails because the service of ViewChild is undefined.

https://stackblitz.com/edit/ng-mocks-examples-tybub8?file=app%2Fapp.component.spec.ts

**Comment by satanTime** [comment]
Hi,

thanks for the request.

I've checked the test and I'll try to figure out how a mocked component might be extended next days.

**Comment by satanTime** [comment]
Hi again,

might you check that `MockInstance` solves the issue for you?

Simply replace `node_modules/ng-mocks` with the content from [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4941811/ng-mocks.zip).

Docs you can find here:
https://github.com/satanTime/ng-mocks/tree/issues/170#mockinstance

A test example: https://github.com/satanTime/ng-mocks/blob/issues/170/tests/issue-170/test.spec.ts

Thank you in advance!

**Comment by RobertasM** [comment]
Hi,

Yes it works, thanks.

**Comment by satanTime** [comment]
Thanks! Feel free to report again if you're facing any issues.
