### ISSUE TITLE
Wrong content on website

### ISSUE THREAD

**Issue by Dixit199213bafna** [ike18t/ng-mocks#1716]
https://ng-mocks.sudo.eu/api/ngMocks/globalKeep

I am in section of globalKeep but in the section it shows info of ngMocks.globalExclude.

![image](https://user-images.githubusercontent.com/53933740/151560036-8fe95c42-1b2c-443d-94f4-e4d3c4905cda.png)

**Comment by satanTime** [comment]
Hi @Dixit199213bafna, thanks for the report!

**Comment by satanTime** [comment]
[v13.0.1](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
