### ISSUE TITLE
Error with MockBuilder and @angular/cdk DragDropModule

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#173]
Hi @satanTime,
When I use **MockBuilder** to test an application with **DragDropModule** from **@angular/cdk**.
I get this error :

`Error: Unexpected value '[object Object]' exported by the module 'MockOfDragDropModule'`

The test run correctly if I use _keep(DragDropModule)_.
You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-dndmodule).
The code works fine in production.

angular.json
Production :
projects -> demo -> architect -> build -> options -> main -> src/main.ts
Testing :
projects -> demo -> architect -> build -> options -> main -> src/main-testing.ts

Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi again :)

Thanks for the report, I'll take a look tonight and I'll try to provide a fix today or later this week.

**Comment by satanTime** [comment]
Min test:

```
"@angular/cdk": "10.0.2",
"@angular/material": "10.0.2",
```

```typescript
import { MockBuilder, MockRender } from 'ng-mocks';
import { DragDropModule } from '@angular/cdk/drag-drop';

import { Component, NgModule } from '@angular/core';

@Component({
  selector: 'app-root',
  template: 'ng-mocks',
})
export class AppComponent {
}

@NgModule({
  imports: [
    DragDropModule,
  ],
  declarations: [AppComponent],
})
export class AppModule {
}

describe('AppComponent', () => {
  describe('mock DragDropModule', () => {
    beforeEach(() => MockBuilder(AppComponent, AppModule));

    it('should create the app', () => {
      expect(() => MockRender(AppComponent)).not.toThrow();
    });
  });
});
```

**Comment by satanTime** [comment]
Hi @cdupetit,

might you verify that the new build [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4949645/ng-mocks.zip) runs on your tests as expected?

**Comment by cdupetit** [comment]
> Hi @cdupetit,
> 
> might you verify that the new build [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/4949645/ng-mocks.zip) runs on your tests as expected?

Hi @satanTime,
This version fix the error and runs tests as expected.
Thanks.
Best regards.

**Comment by satanTime** [comment]
Thanks!
