### ISSUE TITLE
Class attribute directive is ignored on rendered mock directive

### ISSUE THREAD

**Issue by JesseZomer** [ike18t/ng-mocks#176]
I have the following HTML:
```HTML
<div class="dragdrop-preview" [class.extra-class]="someCondition" *cdkDragPreview>...</div>
```
I'm trying to unit test if the extra-class gets added to the div when `someCondition` is true. However for this test i've changed it to: `[class.extra-class]="true"`

the test looks like this:
```javascript
const preview = ngMocks.findInstance(fixture.debugElement, CdkDragPreview) as MockedDirective<CdkDragPreview>;
preview.__render();

// don't know how to get the classes from the preview, so do a normal query
expect(fixture.debugElement.query(By.css('.dragdrop-preview')).nativeElement).toHaveClass('extra-class');
```
I get the following error:
```
Error: Expected <div _ngcontent-a-c64 class="dragdrop-preview ng-tns-c64-0">...</div> to have class 'extra-class'.
```

I expected it to have the `extra-class` class. Am I correct in my assumption that this class attribute directive is ignored when rendering and if so, could this be added, or am I testing the wrong way?

**Comment by satanTime** [comment]
Hi @JesseZomer,

thanks for the report, might you provide a min test? I'll take a look tonight.

**Comment by JesseZomer** [comment]
Sure, I've made a repo here: https://github.com/JesseZomer/ngmocksIssue176
If you run `ng test` the test described above will fail

**Comment by satanTime** [comment]
Hi @JesseZomer,

after changing things that cause template change you need to call detect changes:
```typescript
    preview.__render();
    fixture.detectChanges(); // <-- add this.
```

**Comment by JesseZomer** [comment]
Hello @satanTime, thanks for the reply.

I've tried it with `fixture.detectChanges()` but that makes no difference.
I thought because the query obviously finds an element the fixture.detectChanges makes no difference, so I removed it again.

**Comment by satanTime** [comment]
when I added it in https://github.com/JesseZomer/ngmocksIssue176 there's no failing test anymore. Might you improve the example to show the failure with `fixture.detectChanges()`?

**Comment by JesseZomer** [comment]
That's weird. That made me look at the differences between the reproduction test and the real testcase. 
In the real situation the component has a changedetectionStrategy of OnPush. Because I wasn't changing any @input fields, the class directive probably never gets reapplied. 

When I add 
```javascript
        preview.__render();
        component.input= { ...component.input };
        fixture.detectChanges();
```
it works 🎉 

I probably didn't think of this, because something did get rendered so the HTML had changed.

Thank you for taking the time to help me fix this issue 👏

**Comment by satanTime** [comment]
Glad to hear!
