### ISSUE TITLE
MockBuikder: RouterModule.forChild and multiple components

### ISSUE THREAD

**Issue by cdupetit** [ike18t/ng-mocks#178]
Hi @satanTime,
When I use **MockBuilder** to test a _XComponent_ included in a **RouterModule.forChild** route with a _YComponent_.
I get this error : 

`Error: Component YComponent is not part of any NgModule or the module has not been imported into your module.`

To remove error, I should mock the _YComponent_ manually.
You can see the error in [StackBlitz](https://stackblitz.com/edit/angular-mockbuilder-routing-module).
The code works fine in production.

> _angular.json_
> **Production** :
> projects -> demo -> architect -> build -> options -> main -> `src/main.ts`
> **Testing** :
> projects -> demo -> architect -> build -> options -> main -> `src/main-testing.ts`

Thanks in advance.
Best regards.
Cyril

**Comment by satanTime** [comment]
Hi again,

I hope you are doing great.

Thanks for the report. I'll take a look this weekend and release an update on Sunday.

**Comment by cdupetit** [comment]
I'm on vacation for two weeks starting tonight. So I could not test before my return.

**Comment by satanTime** [comment]
No worries, take your time and have fun!

**Comment by cdupetit** [comment]
Thanks
