### ISSUE TITLE
Bug?  Cannot combine @Input decorators with query decorators

### ISSUE THREAD

**Issue by appienvanveen** [ike18t/ng-mocks#181]
Hi,

im using your lib version 10.1.2 with angular 9.1.2 in combination with the Syncfusion angular framework.

I'm getting the following error when I run my tests: 
`

	Error: Cannot combine @Input decorators with query decorators
	    at http://localhost:9876/_karma_webpack_/D:/Work/Java
`

Code looks like follows:

```
describe('XComponent', () => {
    let component: XComponent;
    let fixture: MockedComponentFixture<XComponent>;
    beforeEach(() => MockBuilder(XComponent, XModule)
        .provide({provide: ControlContainer, useValue: fgd}),
    );
    beforeEach(() => {
        fixture = MockRender(XComponent);
        component = fixture.point.componentInstance;
        fixture.detectChanges();
    });
    it('should create', () => {
        expect(component).toBeTruthy();
        expect(component.controlContainer).toBeDefined();
    });
});
```

I'm not sure if this is caused by the mock framework or by the syncfusion library. Running the project works fine; even as building the project. This just happens when running the tests.

**Comment by satanTime** [comment]
Hi again,

might you share code of XComponent, or create a min code sample with the failing test?

**Comment by appienvanveen** [comment]
[example-bug.zip](https://github.com/ike18t/ng-mocks/files/5117533/example-bug.zip)

Please find a sample project attached :)

**Comment by appienvanveen** [comment]
Any idea yet? @satanTime :)

**Comment by satanTime** [comment]
Hi, unfortunately, didn't check it yet. I'll do that latest on Sunday evening. Sorry for the delay.

**Comment by appienvanveen** [comment]
No problem, take your time :)

**Comment by appienvanveen** [comment]
Any update yet? :)

**Comment by satanTime** [comment]
Checking :)

**Comment by satanTime** [comment]
Hi, I'm investigating it deeper, I have a fix, but I want to find the cause.

**Comment by appienvanveen** [comment]
Ah cool. I was thinking it was caused by the syncfusion library, but since it only occurse during testing/mocking I doubted this.

**Comment by satanTime** [comment]
Yep, the way they are creating components and directives in the lib causes the issue, they use decorators in an interesting manner, but if I do a copy for testing it doesn't fail anymore. So I'll try to dig deeper for understanding of the exact cause.

**Comment by appienvanveen** [comment]
Hi, it appears that when i disable ivy for the test in my tsconfig, the tests run fine.

**Comment by satanTime** [comment]
Ah, that's an awesome hint! Thanks, I'll try this way.

**Comment by satanTime** [comment]
Hi again, might you check if it solves your issue? 
[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5178179/ng-mocks.zip)

**Comment by appienvanveen** [comment]
Works like a charm!

**Comment by satanTime** [comment]
Thanks for checking, I'll release the changes this week.

**Comment by satanTime** [comment]
A new version has been released. Thanks for the report.
