### ISSUE TITLE
Failed: ng-mocks is not in JIT mode and cannot resolve declarations

### ISSUE THREAD

**Issue by viniciostorres** [ike18t/ng-mocks#182]
I'm using Angular 9 and I'm receiving this message on Karma report. Is there a solution?

**Comment by satanTime** [comment]
Hi, thanks for the report.

Might you provide an example with the reproduction of the failure?

**Comment by satanTime** [comment]
Hi @viniciostorres, any update on this?

**Comment by satanTime** [comment]
I'll close the issue, feel free to reopen it with more details.

**Comment by cl-ax** [comment]
I'm having this issue too, and I'm not using the mock in production; only in a Jest test suite.

**Comment by satanTime** [comment]
Hi @cl-ax, great to hear! might you create a sandbox project that reproduces the issue?

**Comment by cl-ax** [comment]
I'll try. It's a pretty heavy setup (legacy code of course) so I don't know how long before I get to it.

**Comment by satanTime** [comment]
@cl-ax, thanks, I very appreciate it. if it worked for you or your company - you can invite me private to the repo, I promise to check only the issue and delete the code right after fixing it.

**Comment by cl-ax** [comment]
Oh man I found the issue. It was my mistake... Under my `import` statements, I had a stray `jest.mock()` for that particular module. So by the time `MockModule` was getting the component, is was a Jest mock and not an Angular module anymore!

**Comment by satanTime** [comment]
Ah, cool, thanks for the info. Should be a helpful finding in future for other developers.

I'll close the issue. Feel free to comment it any time.
