### ISSUE TITLE
Providers mocked via MockModule are persisted across tests

### ISSUE THREAD

**Issue by JoshuaEN** [ike18t/ng-mocks#186]
Hello,

Providers that are part of a Module, when mocked via `MockModule`, appear to use the same instance across all tests.

For example:
```ts
beforeEach(() => {
    TestBed.configureTestingModule({
        imports: [MockModule(ExampleModule)],
    });

    exampleProvider = TestBed.inject(ExampleProvider);
});

it('should not be able to pass state between tests (setup phase)', () => {
    // Set a property on the class to see if it carries over to the next test.
    exampleProvider.a = 11;
});

it('should not be able to pass state between tests (validation phase)', () => {
    expect(exampleProvider.a).toBeUndefined(); // Fails
});
```
*[Full Example](https://github.com/JoshuaEN/ng-mocks-mock-module-provider-mocking-issue/blob/master/src/app/MockModule.spec.ts)*

I would think the expected behavior is that each test would get a new mocked instance of the provider so that one test could not accidentally impact another test (in this way).

Thank you for your time.

P.S. This also applies to when `MockProvider` is used directly, though I understand that to be an internal API.

---

As a note, this cross-test instance sharing not appear to happen when the the module and provider caches are disabled via `ngMocksUniverse.flags`, e.g.:
```ts
beforeAll(() => {
    ngMocksUniverse.flags.delete('cacheModule');
    ngMocksUniverse.flags.delete('cacheProvider');
});
```

**Comment by satanTime** [comment]
Hi, 

thanks for the report. You need to use `beforeEach(() => MockBuilder(ExampleModule))` instead.

**Comment by JoshuaEN** [comment]
Hi,

Thank you for the quick reply!

Using `MockBuilder` appears to work, but calling `ngMocks.flushTestBed()` does not ([here's the change I tried](https://github.com/JoshuaEN/ng-mocks-mock-module-provider-mocking-issue/commit/796efbadee1dfe1060b0e37786e9be39c07e9759)).

Is using `MockBuilder` the recommended approach to mocking?

**Comment by satanTime** [comment]
Hi again,

yes, `MockBuilder` is the recommended approach.

I'll check the code example next days / weeks the issue for improving ng-mocks lib.

**Comment by satanTime** [comment]
Hi, I've tested it further and it doesn't work without mocking either:

```typescript
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [ExampleModule], // without mocking it still fails.
    });

    exampleProvider = TestBed.inject(ExampleProvider);
  });
```

I would suggest to close this one, feel free to reopen it or to post a new one.

**Comment by JoshuaEN** [comment]
Hi, thank you for looking into this.

> Hi, I've tested it further and it doesn't work without mocking either:

Removing the mocking appears to work correctly for me. Here's what I tried: https://github.com/JoshuaEN/ng-mocks-mock-module-provider-mocking-issue/commit/38e4c022d32892d0c19bcdae6005a95e11f1d08a#diff-807a50de61c19b7d9a595c1e9cec0c05

As a note, the tests were originally falling for me after removing the mocking, but for an unrelated reason: Without mocking, the constructors of the real objects were running and thus the value `a` was set to 5 by the constructor (where, when mocked, the constructor would not run and thus `a` would be `undefined` on initialization).

[I also added an object equality check](https://github.com/JoshuaEN/ng-mocks-mock-module-provider-mocking-issue/commit/97ec74e5a86b8faaa02be2af2586c2c4fcfff59e#diff-807a50de61c19b7d9a595c1e9cec0c05), which is maybe more reliable for demonstrating the issue. With mocking, the same instance of the service object is present in both tests. Without mocking, each has a different instance.

**Comment by satanTime** [comment]
aha, now I was able to reproduce the issue and checking for a possible solution.

Thanks!

**Comment by satanTime** [comment]
Hi again, I think I've found the issue and fixed it. Might you verify that it works well for you?
[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5213989/ng-mocks.zip)

**Comment by JoshuaEN** [comment]
> Hi again, I think I've found the issue and fixed it. Might you verify that it works well for you?
> [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5213989/ng-mocks.zip)

Hi, thanks for the quick reply! It works as expected with this fix.

**Comment by satanTime** [comment]
A new version has been released. Thanks for the report.

**Comment by JoshuaEN** [comment]
Thank you!
