### ISSUE TITLE
Component Provider not mocked when no selector

### ISSUE THREAD

**Issue by cheng93** [ike18t/ng-mocks#1876]
Similar to #1507 

Except when no selector, it does not work. I forked the stackblitz and commented out the selector.

https://stackblitz.com/edit/github-tt2yvq-7pd5cj?file=src/test.spec.ts

**Comment by satanTime** [comment]
Hi there,

thanks for the report! I'll take a look on following days.

**Comment by satanTime** [comment]
Yes, this a bug, nice catch! working on its fix.

**Comment by satanTime** [comment]
[v13.0.3](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.3) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
