### ISSUE TITLE
Mocking of structural directives using shorthand syntax

### ISSUE THREAD

**Issue by LukasMachetanz** [ike18t/ng-mocks#1918]
Hey, I am wondering if it is possible to correctly mock **structural directives** which use the [shorthand syntax](https://angular.io/guide/structural-directives#structural-directive-syntax-reference). E.g. something like `*dxTemplate="let cellTemplate of 'actionsCellTemplate'"`. Is this possible? How has `mock(DxTemplateDirective, { render: true })` to be adjusted to support this?

`DxTemplateDirective` is apparently defined like this:

```
export declare class DxTemplateDirective {
    private templateRef;
    private viewContainerRef;
    private renderer;
    private zone;
    dxTemplateOf: any;
    name: string;
    constructor(templateRef: TemplateRef<any>, viewContainerRef: ViewContainerRef, templateHost: DxTemplateHost, renderer: Renderer2, zone: NgZone);
    private renderTemplate;
    render(renderData: RenderData): any;
    static ɵfac: ɵngcc0.ɵɵFactoryDeclaration<DxTemplateDirective, never>;
    static ɵdir: ɵngcc0.ɵɵDirectiveDeclaration<DxTemplateDirective, "[dxTemplate]", never, { "dxTemplateOf": "dxTemplateOf"; }, {}, never>;
}
```

The HTML-Template uses it something like this:

```
 <div *dxTemplate="let cellTemplate of 'actionsCellTemplate'">
    {{ cellTemplate.data }}
 </div>
```

I would like to provide dummy data for `data`.

Any help appreciated. Thanks.

Greets,
Lukas

**Comment by satanTime** [comment]
Hi, it is: https://ng-mocks.sudo.eu/api/MockDirective#advanced-example-with-structural-directives. The main note is that it should be rendered before assertions.

**Comment by LukasMachetanz** [comment]
I understand the mentioned examples, but on my specific use case I don‘t unterstand how to provide the correct value in order that `let cellTemplate of 'actionsCellTemplate'` is evaluated correctly. Unfortunately I have no experience with this **let of** syntax, especially when it comes to mocking. Therefore, I was wondering if someone could give me a hint. I assume that probably the property  `dxTemplateOf` would have to hold some specific data structure for it to work, but I am not sure. Hm.

**Comment by satanTime** [comment]
Hi there,

I've checked your question.
Angular docs say that `let cellTemplate of 'actionsCellTemplate'` means:
- to assign `'actionsCellTemplate'` as input `StructuralDirectiveSelector+'of'`: `dxTemplateOf`
- to assign local context to `cellTemplate` during rendering

In your case, there 2 things to assert:
- that `'actionsCellTemplate'` has been passed as value to `dxTemplateOf` input
- that local context (`cellTemplate.data`) is rendered

```ts
describe('issue-1918', () => {
  beforeEach(() =>
    MockBuilder().mock(TargetDirective, {
      render: {
        // we should not only render the structural directive, but also provide its context variables.
        $implicit: {
          data: 'MOCK_DATA',
        },
      },
    }),
  );

  fit('renders a mock of structural directives', () => {
    const fixture = MockRender(`
     <div *dxTemplate="let cellTemplate of 'actionsCellTemplate'">
       {{ cellTemplate.data }}
     </div>
    `);

    // firstly, let's check that we passed 'actionsCellTemplate' as input value.
    expect(
      ngMocks.findInstance(TargetDirective).dxTemplateOf,
    ).toEqual('actionsCellTemplate');

    // secondly, let's check that MOCK_DATA has been rendered.
    expect(ngMocks.formatHtml(fixture)).toEqual(
      '<div> MOCK_DATA </div>',
    );
  });
});
```

**Comment by satanTime** [comment]
[v13.0.4](https://github.com/ike18t/ng-mocks/releases/tag/v13.0.4) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
