### ISSUE TITLE
Testing setter for mocked directive

### ISSUE THREAD

**Issue by kekel87** [ike18t/ng-mocks#196]
Hello !

We had a bit of delay for the switch to Angular 10, so here is the first problem we encounter 😄 

We usually test RouterLinks like this:

`MyComponent` template to test :
```html
<mat-toolbar color="primary">
  <h1 [routerLink]="['/my-route']">Title here</h1>
</mat-toolbar>
```

`MyComponent` tests init :
```typescript
beforeEach(() =>
  TestBed.configureTestingModule({
    declarations: [
      MyComponent,
      MockComponents(MatToolbar), // Other @angular/materail stuff
      MockDirective(RouterLink) // RouterLink
    ],
  });

  fixture = TestBed.createComponent(MyComponent);
  ...
);
```

`MyComponent` routerLink test :
```typescript
it(`should routerLink, () => {
  expect(fixture.byCss('h1').injector.get(RouterLink).routerLink).toEqual(['/my-route']);
});
```

Following the Angular 10 transition this no longer works: `Error: Expected undefined to equal ['/my-route'].`

Looking at the Angular team to switch routerLink to a setter : [Here](https://github.com/angular/angular/blob/dbfb50e9f4fe48050b2ab59d19ccd2438c14cc97/packages/router/src/directives/router_link.ts#L196)

And according to this [PR](https://github.com/ike18t/ng-mocks/pull/81) we skipping mocking of getters and setters.

**What solution do we have for this case ?**

For the moment I have found a workaround:
`MyComponent` tests init :
```typescript
beforeEach(() =>
  TestBed.configureTestingModule({
    declarations: [
      MyComponent,
      MockComponents(MatToolbar), // Other @angular/material stuff
      MockDirective(RouterLink) // RouterLink
    ],
  });

  MockInstance(RouterLink, {
    init: (instance, injector) => {
      Object.defineProperty(instance, 'routerLink', { writable: true }); // I say here that it is not a setter.
    },
  });

  fixture = TestBed.createComponent(MyComponent);
  ...
);
```

This allows us to continue to do a simple test:
```typescript
it(`should routerLink, () => {
  expect(fixture.byCss('h1').injector.get(RouterLink).routerLink).toEqual(['/my-route']);
});
```

**What do you think of this solution?**

Thank you !

**Comment by satanTime** [comment]
Hi again.

I think you are trying to do the same as we show here: https://github.com/ike18t/ng-mocks#extensive-example-of-mocks-in-angular-tests

I would suggest something like
```typescript
beforeEach(() => MockBulder(MyComponent, ItsModule).mock(ModuleImportsRouterIfItIsNotInItsModule));

it(() => {
  const fixture = MockRender(MyComponent);
  const element = ngMocks.find(fixture.debugElement, 'h1');
  const actual = ngMocks.input(element, 'routerLink');
  expect(actual).toEqual(['/my-route']);
});
```

**Comment by satanTime** [comment]
About skipping mocks of getters and setters - it has been fixed and now they are properly mocked with respect of assigned values despite a missed getter / setter in the original implementation: https://github.com/ike18t/ng-mocks/commit/5a0ac7c44d4c73d33ab4dad9ad583e31ad28ec5d

**Comment by kekel87** [comment]
Oh yes, I hadn't seen that ! It works perfectly !

Thank you very much !

**Comment by satanTime** [comment]
You are welcome, feel free to ask any questions.
