### ISSUE TITLE
MockBuilder add import

### ISSUE THREAD

**Issue by kekel87** [ike18t/ng-mocks#197]
Hello again !

First of all, do you have a Gitter or a Discord to ask this kind of question and avoid creating issues every time ?

We are trying to use `MockBuilder`, it looks great!

But, we are unable to import unmocked modules that are not part of the component module.

Here the original `TestBed`:
```typescript
TestBed.configureTestingModule({
  declarations: [
    MyComponent,
    MockComponents(MatToolbar, MatIcon),
    MockDirective(MatIcon)
  ],
  imports: [
    // StoreModule come from App top Module
    StoreModule.forRoot(reducers, { runtimeChecks: environment.storeRuntimeChecks }),
    StoreModule.forFeature(featureReducers.featureKey, featureReducers.reducer)
  ],
  providers: [
    { provide: MyService, useValue: mockMyService },
  ],
})
```

Here the equivalent with `MockBuilder`:
```typescript
MockBuilder(MyComponent, ItsModule)
      // I tried this but it doesn't work
      .keep(StoreModule.forRoot(reducers, { runtimeChecks: environment.storeRuntimeChecks }))  // Try also , { export: true }
      .keep(StoreModule.forFeature(featureReducers.featureKey, featureReducers.reducer)) // Try also , { export: true }
      .mock(MyService)
```

Can you help me on that ?

**Comment by satanTime** [comment]
Hi again,

unfortunately, `NgModuleWithProviders` isn't supported yet.

What you can try to do something like that currently:

```typescript
const ngModule = MockBuilder(MyComponent, ItsModule)
      .mock(MyService).build(); // it only creates ngModule def without configuring TestBed.

// now we can add NgModuleWithProviders dependencies
ngModule.imports = [
  ...ngModule.imports,
  StoreModule.forRoot(reducers, { runtimeChecks: environment.storeRuntimeChecks }),
  StoreModule.forFeature(featureReducers.featureKey, featureReducers.reducer),
];

// and configure TestBed
return TestBed.configureTestingModule(ngModule).compileComponents();
```

Please let me know whether it works for you, and also, please, don't close the ticket, I'll try to find a solution on the weekend.

**Comment by satanTime** [comment]
about `Gitter` or `Discord`, unfortunately, not. This project is supported on enthusiasm and the way via github issues is the best for now.

**Comment by kekel87** [comment]
OK great, thank you.

I tested your solution it works perfectly!

```typescript
beforeEach(() => {
  const ngModule = MockBuilder(MyComponent, ItsModule)
    .mock(MyService, mySpyService).build();

  return TestBed.configureTestingModule({
    ...ngModule,
    imports: [
      ...ngModule.imports as [],
      StoreModule.forRoot(reducers, { runtimeChecks: environment.storeRuntimeChecks }),
      StoreModule.forFeature(featureReducers.featureKey, featureReducers.reducer),
    ]
  });
});
```

Thank you for your responsiveness !

**Comment by satanTime** [comment]
Glad to hear, you are welcome.

One question if you don't mind.
`StoreModule` - if it's imported, how do you use it in tests? Do you mock it or keep it?

I'm looking for all possible options of usage of `NgModuleWithProviders` and how people would like to tune it in their tests.

**Comment by kekel87** [comment]
In accordance with what [ngrx recommends](https://ngrx.io/guide/store/testing), we test once in a purely unit fashion by completely mocking `StoreModule` with `provideMockStore` (provide by ngrx).

And it works great with MockBuilder:
```typescript
  beforeEach(() => {
    MockBuilder(MyComponent, ItsModule)
      .provide(provideMockStore({ initialState: { [featureReducer.featureKey]: featureReducer.initialState } }))
      .mock(MyService, mySpyService)
  });
```

And another time, integrate `StoreModule` without mocking it as requested in this issue.

**Comment by satanTime** [comment]
Aha, good to know. but why `StoreModule.forRoot` is needed in the original test? isn't provideMockStore enough for tests?

**Comment by kekel87** [comment]
Historically we tested with `StoreModule.forRoot`, now we try to do as ngrx [recommends](https://ngrx.io/guide/store/testing#integration-testing).

But we must continue to test with `StoreModule.forRoot` to test the correct integration.

**Comment by satanTime** [comment]
Thanks, I think I have a better picture now and can work on improvements of the lib.

**Comment by gituser3000** [comment]
Probably 1 more case:
```
     service.doSmthAndNavigate());
     tick();
     let location = TestBed.get(Location);
     expect(location.path()).toBe('/myRoot/666');
```
Testing that routing works as planned

**Comment by kekel87** [comment]
Hi

It would also be good if the `MockBuilder().mock()` function supports abstract classes such as `DomSanitizer` or `Renderer2`.

![image](https://user-images.githubusercontent.com/22544289/95565570-b06b8600-0a20-11eb-93c8-622d693711a6.png)

Thanks!

**Comment by kekel87** [comment]
No wait, it's work like this: `provide({ provide: DomSanitizer, useValue: domSanitizer })`

**Comment by satanTime** [comment]
It's a good case - I'll add it too.

**Comment by satanTime** [comment]
Hi @kekel87,

might you verify that both of the issues are properly solved here: [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5355787/ng-mocks.zip)?

now you can keep and mock modules with providers and pass anywhere abstract classes like DoSanitizer.

**Comment by kekel87** [comment]
Sorry for late response ! It's work perfectly, thanks a lot !
