### ISSUE TITLE
Mocking private service in component

### ISSUE THREAD

**Issue by gituser3000** [ike18t/ng-mocks#198]
Hello! Thank you for the great library :)
The question is how to modify the mock of service in the tested component.
I have tried to use MockInstance, but looks like it only works for mocked components.
Example:
```
@Component({
  selector: 'test',
  templateUrl: './test.html'
})
export class ComponentToTest {
 constructor(private _configLocal: TmConfigLocalService){}

public afterViewInit(){
  this._configLocal.treeItems$.subscribe();
}
}
```

What I have tried:
```
  beforeEach(()=>{
    MockInstance(ComponentToTest , {
      init: (_instance, injector) => {
        injector!.get(TmConfigLocalService).treeItems$ = of([]);
      },
    });
  })

  it('should create', () => {
    const fixture = MockRender(ComponentToTest); // error
    expect(fixture.point.componentInstance).toBeDefined();
  });
```

**Comment by satanTime** [comment]
Hi, 

you were quite close :)

I guess what you are looking for is:
```typescript
    MockInstance(ComponentToTest , {
      init: (_instance, injector) => {
        _instance.treeItems$ = of([]);
      },
    });
```

**Comment by satanTime** [comment]
Please leave the issue open, I'll update docs for a better example.

**Comment by gituser3000** [comment]
`Property 'treeItems$' does not exist on type 'ComponentToTest'.`
This property is inside _configLocal.

**Comment by satanTime** [comment]
ah, true sorry,

```
MockInstance(TmConfigLocalService, { // <- we need to customize TmConfigLocalService, not ComponentToTest.
  init: instance => {
    instance.treeItems$ = of([]);
  },
});
```

**Comment by gituser3000** [comment]
Wow, this was unexpected 👍 
Additional info:
TmConfigLocalService is not provided in componentToTest module, but is global. So I had error
`No provider for TmConfigLocalService!`
In order to handle it i was using provide:
`  .provide({provide: TmConfigLocalService, useValue: MockService(TmConfigLocalService)})`
  
but mockInstance above gave no impact, until I used:
`.mock(TmConfigLocalService)`
instead of provide
Was am I wrong using 'provide'?

**Comment by satanTime** [comment]
That's right,

if you use `useValue` - then ngMocks doesn't touch provided value.

if you use `.mock(TmConfigLocalService)` - it's a bit more intelligent than `MockService(TmConfigLocalService)` and causes a call of `MockInstance` on initialisation of `TmConfigLocalService`. Because it uses a factory https://github.com/ike18t/ng-mocks/blob/master/lib/mock-service/mock-service.ts#L336-L343, `config.init(instance, injector);` - of your init function.

**Comment by gituser3000** [comment]
Thank you!

**Comment by satanTime** [comment]
update my comment.

**Comment by gituser3000** [comment]
items in mock are 'any'. Is it by design?

**Comment by satanTime** [comment]
It tended to be like that, but we can reconsider being `Partial<T>`. Might you provide your example why `any` is a problem / issue here?

**Comment by gituser3000** [comment]
Probably not an issue, but a thing to improve?
1) More type-friendly (improved ide experience)
2) Will show errors if an attribute was deleted (and a test was broken?)
3) Will work the same way, as MockInstance do

**Comment by satanTime** [comment]
Original plan was if people want to mock private things, but I guess it doesn't make sense and `Partial<T>` would be a good fit. I'll update it on the weekend too.

**Comment by gituser3000** [comment]
`mock?: Partial<T> & {[key: string]: any}` <- will not break mocks of private properties and will help IDE )

**Comment by satanTime** [comment]
thanks, I play with it on the weekend and release an update on.
