### ISSUE TITLE
github issue template

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#2088]
It should contain links how to create a min repo on stackblitz / codesandbox.

**Comment by GerkinDev** [comment]
You might use something like this: https://stackblitz.com/edit/github-ytvy85-gv1rtf?file=src%2Ftest.spec.ts

It is simply a copy of your examples stackblitz, but with most files deleted. I just kept style & setup related files.

**Comment by satanTime** [comment]
Hi there,

Thanks for your help, my plan was the same with the difference to do it in the example repo as a separate branch:
- master - as it is
- base - only setup without tests

**Comment by GerkinDev** [comment]
Hi,

Yeah, ofc, this would allow keeping versions in sync & use CI pipelines (I guess you have some), so this is way better.

Ideally, IMO even more files should be hidden/removed from the files tree, to keep the strict minimum.

**Comment by satanTime** [comment]
[v13.4.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.4.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
