### ISSUE TITLE
`findInstances` inconsistent behavior: should it select instances in first of selector or all ?

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#2105]
Heya ! It's me again !

So, I've rendered a component in which I want to select several instances of directives by selector, and I stumbled on a little inconsistency.

Here is the repro: https://stackblitz.com/edit/github-ytvy85-gfwzxj?file=src/test.spec.ts

Seing this: https://github.com/ike18t/ng-mocks/blob/57471fc88f342099cf000d998a634138f457c718/libs/ng-mocks/src/lib/mock-helper/find-instance/mock-helper.find-instances.ts#L19

Instances are returned from the 1st selector match. I would have assumed that it would return instances in all matching CSS selectors (see the 2nd test). 

I know you've specified from the docs:

> A css selector helps to find the first matched element. It will be used to look up the desired declaration.

But I don't see the cons of selecting all instances in all matching selectors. Just needs to have selectors specific enough.

Cheers !

**Comment by satanTime** [comment]
Hi there, agree with you.

**Comment by satanTime** [comment]
[v13.3.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.3.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
