### ISSUE TITLE
Is `Expected to be running in 'ProxyZone', but it was not found.` a common error?

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#2195]
I am upgrading to angular 13 and upgrading ng-mocks from 12.5.0 to 13.4.0. This seems to come from importing 'zone.js/testing', which is not a requirement from angular 13 but from ng-mocks 13, so that is why I ask. I am having a difficult time finding any documentation about this error other than it's supposedly related to `FakeAsync`, which I am not using in any of my tests.

__Originally posted by @neilsoult in https://github.com/ike18t/ng-mocks/issues/782#issuecomment-1090625140__

**Comment by satanTime** [comment]
Hi @neilsoult, 

could you provide me a min repo where it doesn't fail?

once I have a test, I'm getting: `Error: zone-testing.js is needed for the fakeAsync() test helper but could not be found.`, even I don't use `ng-mocks`.

```ts
import { TestBed } from '@angular/core/testing';

import { AppComponent } from './app.component';
import { AppModule } from './app.module';

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [AppComponent],
      imports: [AppModule],
    });
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    expect(fixture.componentInstance).toBeTruthy();
  });
});
```

**Comment by satanTime** [comment]
Also, in angular code it requires `zone`:

https://github.com/angular/angular/blob/master/packages/core/testing/src/test_hooks.ts#L37-L40

because above it calls it with `true` and `false`, so one of them will trigger the reset of `resetFakeAsyncZone` anyway.

**Comment by neilsoult** [comment]
I'm trying to create a repro but I'm coming across the same errors and I'm haven't even added ng-mocks and I'm getting the same errors, so it's leading me to believe this is not a problem with ng-mocks. 

Even though I'm not using `FakeAsync` anywhere in my code, I get the error 
```
zone-testing.js is needed for the fakeAsync() test helper but could not be found.
            Please make sure that your environment includes zone.js/testing
```
and when I add 
```
import 'zone.js';
import 'zone.js/testing';
```
to test-setup.ts, I then get the error 
```
 Expected to be running in 'ProxyZone', but it was not found.
```

I'll keep trying to repro but it doesn't appear to be ng-mocks related.

**Comment by satanTime** [comment]
Thanks for confirming. Then I'm going to close the ticket. Please share you findings.

There are configs for A13 in `ng-mocks`: https://github.com/ike18t/ng-mocks/tree/master/e2e/a13
