### ISSUE TITLE
Auto-import from ng-mocks doesn't work (VS Code)

### ISSUE THREAD

**Issue by cyberbiont** [ike18t/ng-mocks#2198]
### Description of the bug

Cannot use auto-import in VS Code like with all other packages

### Expected vs actual behavior

E.g. if I use MockBuilder somewhere in my code and it's not defined (typescript says 'cannot find name 'MockBuilder'.ts(2304)'  I expect that pressing 'Quick fix' button will present me an option 'add import from "ng-mocks", that automatically adds `import { MockBuilder } from 'ng-mocks'` line.
Tried it in several projects.

Usually this feature work perfectly for other packages, probably it's something related to the way the exports are done from 'ng-mocks'.

Listing all imports manually each time is kind of annoying.

**Comment by satanTime** [comment]
Hi there. Actually it should, that's what I always do. 

Could you describe steps and specify IDE its version and related plugins?

**Comment by satanTime** [comment]
Hi @cyberbiont,

could you verify that this version works correctly? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/8445834/ng-mocks.zip)

**Comment by cyberbiont** [comment]
Sorry, false alarm. 
Seems like you can auto-import something only if somewhere in your project you already have at least one import from this module. 
I hadn't imported anything from 'ng-mocks' by then so it didn't work until I did it manually first time.
 
I think we can close it

**Comment by satanTime** [comment]
Ah. I see. It's good to know, because I saw time to time I can import and time to time cannot, and at least one import explains it. 

Also, feel free to comment if you have any feedback or concerns.

**Comment by satanTime** [comment]
[v13.4.1](https://github.com/ike18t/ng-mocks/releases/tag/v13.4.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
