### ISSUE TITLE
(better) support for RXJS subscriptions

### ISSUE THREAD

**Issue by Martinspire** [ike18t/ng-mocks#226]
So when you mock a component or service that contains or has functions that return a subscription, it becomes difficult to easily test that with a mocked component.

Now I get that RXJS isn't a mandatory part of Angular, but seeing how many people use it now, I feel that the types/functions should be supported to mock the response or have a way to inject a value when the mocked component is set up.

Either that or the readme should have more detail on how to easily do this, as there's lots of folks that want to do this. Especially when the ngOnInit triggers a subscription, it requires more code to get some data in your mocked component before your first test, but you'd rather inject the data in your test so you have more control over executing multiple use cases.

I'm not entirely sure how the code should look like, but I feel that right now I can't really use ng-mocks whenever there is a subscription in my service that the oninit of my component that I'm testing, is going to call for.

So when a service has a function that returns a subscription, I'd like ng-mocks to recognize that and initialize the subscription (with an empty value to start with, or some way to provide the initial value), so I can do something with that.

Right now you'd often get a `TypeError: Cannot read property 'subscribe' of undefined` because the value isn't initialized as a subscription. The cop-out would be to just inject the service and go from there but thats not really black-box testing

**Comment by satanTime** [comment]
Hi @Martinspire, 

thanks for the report. Might you provide an example of the code you want to test? Usually you might use `MockProvider`, `.mock` or `MockInstance` for that and provide an observable the code requires.

Unfortunately, return types exist only in typescript code. Therefore in javascript runtime we don't have them, and I don't know a solution to detect them. That's why angular uses decorators, it allows to collect information about constructors and DI.
If you know - please share it and I'll be glad to work on its integration.

There is `MockInstance` to help with that for such cases.
It's quite hard, if it is even possible, to predict what should be returned and how it should behave and only developers know the right answer.

What I usually do is:

```typescript
MockBuilder(Component, Module).mock(Service, {prop$: EMPTY});
```

or in case of more complicated cases

```typescript
MockInstance(Service, {
  init: (service, injector) => {
    service.prop$ = of(injector.get(TOKEN));
  }
});
```

or like that.

**Comment by satanTime** [comment]
From your suggestions, I can add a section in readme how to mock observables in constructors and lifecycle hooks.
If it helped.

**Comment by satanTime** [comment]
Hi @Martinspire,

might you check whether the section fits your expectations? https://github.com/satanTime/ng-mocks/tree/issues/226#how-to-fix-typeerror-cannot-read-property-subscribe-of-undefined

**Comment by satanTime** [comment]
A test example is here: https://github.com/satanTime/ng-mocks/blob/issues/226/examples/MockObservable/test.spec.ts

**Comment by satanTime** [comment]
[v10.5.3](https://github.com/ike18t/ng-mocks/releases/tag/v10.5.3)
has been released and contains a fix for the issue.
Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by satanTime** [comment]
Hi @Martinspire,

I hope this finds you well.

I think I found a way to implement what you described: https://github.com/satanTime/ng-mocks/tree/features/default-mock#ngmocksdefaultmock

Might you check if this fits your expectations? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5625707/ng-mocks.zip)

Here you can find examples for tests: https://github.com/satanTime/ng-mocks/tree/features/default-mock/tests/ng-mocks-default-mock

Looking forward to hearing from you.

**Comment by satanTime** [comment]
[v11.2.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.2.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Martinspire** [comment]
Sorry for the lack of activity. Just checked a few links and they were not found but I just looked at the 2 releases and it fixes my issue very nicely. Thanks for the help and explanation!

**Comment by satanTime** [comment]
Hi @Martinspire,

glad to see you back :)
I'll fix the links for needs of other users.

Might you provide a feedback or drop a few words how `ngMocks.defaultMock` works for you, whether there are some obstacles you are facing, and if you wanted to improve something?

Thank you in advance!

**Comment by Martinspire** [comment]
I've only done work on a few tests lately, but it seems to have fixed my issues and improved a few other things too. I do think I won't always use defaultMock as I still prefer to mock only what I need for my tests, but for some generic functions it seems to provide an easy interface. Thanks for the work and thanks for the feedback. Much appreciated!
