### ISSUE TITLE
Bug: ngMocks.findInstance does not find AsyncPipe in structural directive

### ISSUE THREAD

**Issue by parloti** [ike18t/ng-mocks#2314]
### Description of the bug

ngMocks.findInstance does not find AsyncPipe in structural directive like ngIf and ngFor, regardless of whether element is displayed or not.

### A repo with an example of the bug

Link: [stackblitz](https://stackblitz.com/edit/github-ytvy85-hdcxuq?file=src/test.spec.ts)

### Expected vs actual behavior

ngMocks.findInstance should find the pipe used in the structural directive.

**Comment by satanTime** [comment]
Hi @parloti,

thanks for the report.

I think, the issue comes because of `*` sugar, because the real template is like that:

```ts
<ng-container [ngFor]="... | async">
    <div class="array">
      item: {{ item }}
    </div>
</ng-container>
<ng-container [ngIf]="... | async">
    <div class="false>false</div>
</ng-container>
<div class="text">{{ text$ | async }}</div>
<ng-container [ngIf]="... | async">
    <div class="true">true</div>
</ng-container>
```

and therefore the search should be done on `ng-container` instead of inner nodes.

Anyway, I'll take a look what can be done.

**Comment by satanTime** [comment]
So, I added "hungry" behavior, if a found element has a "structural directive" on its parent, then the parent also will be scanned.

It won't work with `.false`, because its dive isn't rendered. However, it's possible to find its `ngIf` and fetch the pipe from it.

Could you test if it does what you expect? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/8549970/ng-mocks.zip)

**Comment by parloti** [comment]
Perfect!
All pipes are found with ngMocks.findInstance**S**, I can get the _'.false'_ here.


I can also change 
`<div class="false" *ngIf="false$ | async">false</div>`
 to 
`<div class="false"><div *ngIf="false$ | async">false</div></div>` 
 and it works too.
 
 Thank you very much.

**Comment by satanTime** [comment]
thanks for feedback, I ran out of CI/CD minutes, for the fix will be released on the first weekend in May :) meanwhile, I'll adapt the fix for all angular versions.

**Comment by satanTime** [comment]
[v13.5.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
