### ISSUE TITLE
Facing issue while trying to use MatCheckboxModule

### ISSUE THREAD

**Issue by emailvenkatm** [ike18t/ng-mocks#239]
beforeEach(() => {
   return MockBuilder(component, AppModule)
   .keep(ReactiveFormsModule)
   .keep(MatCheckboxModule)
    .mock(...)
});

Getting the below error 
TypeError: Cannot read property 'subscribe' of undefined
    at MatCheckbox.ngAfterViewInit (

I feel like using ngmocks without the material modules seems to be very cool. But if we want to keep material modules with ngmocks looks like there seems to be many issues.

Even I try to use MatIconModule it is giving error like "TypeError: Cannot read property 'nodeName' of undefined
    at new SvgIconConfig ". 

Please help..

**Comment by satanTime** [comment]
Hi,

Thanks for the report. Might you provide a sample repo with the issue?

**Comment by satanTime** [comment]
I've created a playground, but it doesn't fail https://codesandbox.io/s/zen-cohen-qbgur?file=/src/test.spec.ts

Are you on the latest version? I think around 10.5.2 there was a similar issue, and it was fixed in 10.5.3 or 10.5.4.

**Comment by satanTime** [comment]
Hi @emailvenkatm, any update on this?

**Comment by satanTime** [comment]
Hi @emailvenkatm, feel free to reopen the issue when you have more details or time to discuss it. I'll close it for now.
