### ISSUE TITLE
Support of impure pipes

### ISSUE THREAD

**Issue by parloti** [ike18t/ng-mocks#240]
https://github.com/ike18t/ng-mocks/blob/2e8f5cf1cf57f202c726a07dcb45f3720e6a7644/lib/mock-pipe/mock-pipe.ts#L23

Whether a pipe is impure or not affects my tests, however `MockPipe` ignores this information.

It makes more sense to me that the line above is simply:

  `@Pipe(coreReflectPipeResolve(pipe))`

**Comment by satanTime** [comment]
Hi! 

thanks for the report! I've been always thinking about that part. might you give me an example when you need a mock pipe to be impure? Because I wasn't able to figure out it myself.

**Comment by parloti** [comment]
```
const pipe = findPipeInstance(...);
const translation = Random.string(10);
const spy = spyOn(pipe, 'transform').and.returnValue(translation);

fixture.detectChanges(); <--- (*)

expect(spy).toHaveBeenCalledWith(key);
expect(comp.textContent).toBe(translation);
```

(*) As I already called `fixture.detectChanges`, this will have no effect because the pipe is pure, that is, angular will not call 'transform', because the `key` argument has not been changed. At the end textContent remain with the original value and the spy will not be called.

Ref: [PurePipe](https://angular.io/api/core/Pipe#pure)

**Comment by satanTime** [comment]
Yep right, I just was wondering about the case, because the code looks like an attempt to set `pipe.transform` behavior, but it doesn't follow the intention of the issue :) 

Just to confirm. In your test you want to assert that the `pipe.transform` has been called again despite the pipe's string hasn't been changed. Is that correct?

If it's so, I'll fix it with the next release.


Thanks.

**Comment by parloti** [comment]
> Yep right, I just was wondering about the case, because the code looks like an attempt to set `pipe.transform` behavior, but it doesn't follow the intention of the issue :)

You are right! I am contaminated by the problem :).

> Just to confirm. In your test you want to assert that the `pipe.transform` has been called again despite the pipe's string hasn't been changed. Is that correct?

Yes, and this is what always happens with an impure pipe, which is precisely the case I am working on now.
For issues beyond my reach, I need to verify that:
1 - 'transform' of the current instance was called with the specified argument.
2 - if the value returned by the pipe was associated with the specified element.

Using the second `MockPipe` argument is not an option because I am working with a specific instance of the pipe, not with the prototype.

> Maybe code like that:
> 
> ```ts
> fixture.detectChanges();
> fixture.detectChanges();
> fixture.detectChanges();
> 
> expect(spy).toHaveBeenCalledWith(key);
> expect(spy).toHaveBeenCalledTimes(4);
> ```

More or less.

I have several tests in the same suite and almost all require

 ```
 beforeEach (() => {
     fixture.detectChanges ();
   });
```

In some cases the element that uses the pipe will only be redenrized after detectChanges, and consequently 'transform' will be called, before I can spy.

**I think my specific case is way beyond the 'MockPipe' functions, but I wouldn't have the problem with impure pipes if 'MockPipe' didn't discard part of the metadata.**

Thanks.

**Comment by satanTime** [comment]
Got it, thanks for the info. I'll keep the flag when creating a mock copy, and also check how we might distinguish the same pipe but its different instances.

**Comment by satanTime** [comment]
Hi @parloti,

I hope this finds you well.

Might you verify that the changes do what you want them to do? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5622253/ng-mocks.zip)

Besides that I extended `ngMocks.get` and `ngMocks.findInstance(s)` to detect pipes.
Now you can simply get them like:
```typescript
const pipeFromAnElement = ngMocks.get(ngMocks.find('span.some'), MyPipe);
const allPipes = ngMocks.findInstances(MyPipe);
const pipesInDiv = ngMocks.findInstances(ngMocks.find('div.with-pipes'), MyPipe);
```

**Comment by satanTime** [comment]
[v11.2.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.2.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by parloti** [comment]
Sorry for the delay, I had to take a long vacation.
Thanks, this works exactly as expected.

**Comment by satanTime** [comment]
Hi @parloti,

I hope you had a good one.

Thanks for the update.
