### ISSUE TITLE
ngMocks.guts() does not create mocks for declarables exported from other modules

### ISSUE THREAD

**Issue by wvankoppen** [ike18t/ng-mocks#241]
ngMocks.guts() does not create mocks for declarables exported from other modules.

This happens when a module is imported that **exports** a declarable (a component, directive or pipe) that it does not **declare** in itself.

This leads to the following error: 
_Error: Can't export pipe MockOfTranslatePipe from MockOfMyTranslateModule as it was neither declared nor imported!_

Reproduction steps:

```
@NgModule({
  declarations : [
    AppComponent
  ],
  imports : [
    BrowserModule,
    MyTranslateModule // <- This module exports TranslatePipe but does not declare it!
  ],
  providers : [],
  bootstrap : [AppComponent]
})
export class AppModule {
}

```

```
@NgModule({
    imports: [TranslateModule],
    declarations: [],  // <- TranslatePipe is NOT declared because it is imported from TranslateModule
    exports: [TranslatePipe],
})
export class MyTranslateModule {}```

**Comment by satanTime** [comment]
Hi @wvankoppen,

thanks for the report, a good catch, its fix will be release with the next version.

**Comment by satanTime** [comment]
Hi @wvankoppen,

I hope this finds you well.

might you verify the fix? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5624361/ng-mocks.zip)

Thanks in advance!

**Comment by wvankoppen** [comment]
Hi @satanTime,

Thanks for your quick reply!
I'm happy to see that the fix works like a charm!
Please let me know when the new release is coming :)

Regards Wouter

**Comment by satanTime** [comment]
Hi @vespertilian, 

thanks for the feedback. It will be released on Saturday / Sunday.

**Comment by wvankoppen** [comment]
Wonderful, thanks!

**Comment by satanTime** [comment]
[v11.2.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.2.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
