### ISSUE TITLE
Cannot read property 'ngModule' of undefined

### ISSUE THREAD

**Issue by wvankoppen** [ike18t/ng-mocks#248]
I have the following setup: I like to test the ProfileOverviewComponent and create mocks for all declarables in its module, which is the ProfileOverviewLazyLoadedModule.

```
 beforeEach(async(() => {
        const metadata = ngMocks.guts(ProfileOverviewComponent, ProfileOverviewLazyLoadedModule);
        metadata.providers.push({ provide: Store, useValue: storeMock });
        TestBed.configureTestingModule(metadata).compileComponents();
    }));
```

But now the test shows the following error: Failed: Cannot read property 'ngModule' of undefined
![image](https://user-images.githubusercontent.com/1695270/101596232-0050d400-39f5-11eb-9c47-8f67f10f23e1.png)

The ProfileOverviewLazyLoadedModule imports around 15 other modules, which have declarables on their own (that need to be mocked in this case). I think some module lookup t read the metadata of the module might be incorrect?

**Comment by satanTime** [comment]
Hi @wvankoppen,

thanks for the report.

I think I've caused that with latest changes because, ideally there shouldn't be `undefined` provided. But looks like it is :)
Maybe try for now 11.0.0 or 11.1.0, I assume that one of them doesn't have the issue.

I'll rollback changes this evening and provide you a package for the verification, if it works on the weekend it will be released.

**Comment by satanTime** [comment]
Might you try if it solves the issue? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5664138/ng-mocks.zip)

**Comment by wvankoppen** [comment]
Thanks for the quick reply!
Downgrading to 11.0.0 or 11.1.0 is unfortunately not an option, because I need [this ](https://github.com/ike18t/ng-mocks/issues/241)fix as well.

I'll try the zip file and let you know whether it works :)

**Comment by wvankoppen** [comment]
The zip works, thanks! Could you release it?

**Comment by satanTime** [comment]
@wvankoppen, thanks, glad to hear! I need to cover the fix with tests and will release it on the weekend.

**Comment by satanTime** [comment]
[v11.2.3](https://github.com/ike18t/ng-mocks/releases/tag/v11.2.3) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
