### ISSUE TITLE
Bug: MockBuilder.mock component that extends a service results in mock that's placed in providers rather than declarations

### ISSUE THREAD

**Issue by DmitryEfimenko** [ike18t/ng-mocks#2646]
### Description of the bug

Let's say we have a component that extends a service. Trying to call `MockBuilder.mock(MyComponent).build()` on that component results in the component mocked as a service and placed in the providers. Please see the repro link.
I suspect that similar behavior would be observed if we call `.keep(...)`

### A repo with an example of the bug

Link: https://codesandbox.io/s/cool-swartz-f4nnwz?file=/src/test.spec.ts

### Expected vs actual behavior

The mocked component should end up in `declarations`

**Comment by satanTime** [comment]
Hi. Thanks for reporting the issue. I'll try to fix it today.

**Comment by satanTime** [comment]
is it only Service -> Component in your projects, or you have other combinations?

**Comment by satanTime** [comment]
Hi @DmitryEfimenko, could you check whether the fix works well on your project?
[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/8825193/ng-mocks.zip)

**Comment by DmitryEfimenko** [comment]
The issue with the component that extends a service is fixed. Thanks! However, I still am experiencing an issue where I have to explicitly import ReactiveFormsModule.
Here's repro: https://codesandbox.io/s/vibrant-tree-6ghgh8?file=/src/test.spec.ts (like described in #2647).
We can probably close this issue and re-open the other one... or just discuss it here. Up to you!

**Comment by satanTime** [comment]
I see. Good. I've reopened that one. Please try to find a way how I could reproduce it on my side.

**Comment by satanTime** [comment]
[v14.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v14.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
