### ISSUE TITLE
Support selector-less components

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#266]
Hey there ! It's me again.

By fooling around with ng-mocks in my app's tests, I've found that ng-mocks does not correctly set the fixture's `point` property correctly if the tested component has no selector (like a page-only component).

Here is the failing test case: 

```ts
import { Component } from '@angular/core';
import { MockBuilder, MockRender } from 'ng-mocks';

@Component({
  template: `<span>Hello world</span>`,
})
class TestedComponent {}

describe('MockRender', () => {
  beforeEach(() => MockBuilder(TestedComponent));

  it('should get the rendered component correctly if no selector', () => {
    const fixture = MockRender(TestedComponent);
    expect(fixture.point).toBeDefined();
  });
});
```

I've found a way to go around this issue like so (this test works)

```ts
import { Component, ɵReflectionCapabilities } from '@angular/core';
import { MockBuilder, MockRender } from 'ng-mocks';

@Component({
  template: `<span>Hello world</span>`,
})
class TestedComponent {}

describe('MockRender', () => {
  const TestedComponentWithSelector = Component({
    ...new ɵReflectionCapabilities().annotations(TestedComponent)[0],
    selector: 'this-can-be-anything'
  })(TestedComponent)
  // Do not forget to return the promise of MockBuilder.
  beforeEach(() => MockBuilder(TestedComponentWithSelector));

  it('should get the rendered component correctly', () => {
    const fixture = MockRender(TestedComponentWithSelector);
    expect(fixture.point).toBeDefined();
  });
});
```

> Note: the weird bit using angular internal reflector is taken from [here](https://github.com/ike18t/ng-mocks/blob/368db2cfe4e644786a21080eaf0a89f308a128d9/lib/common/jit-reflector.ts)

:beers: cheers !

**Comment by satanTime** [comment]
Hi again!

Thanks for the report! I'll fix it during the next days.

Happy New Year and happy coding!

**Comment by satanTime** [comment]
Hi @GerkinDev,

might you confirm it works as you expect? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/5755925/ng-mocks.zip)

**Comment by satanTime** [comment]
[v11.3.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.3.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by GerkinDev** [comment]
Hi, sorry for not answering earlier. I see you like this : ![https://tenor.com/ba5gS.gif](https://tenor.com/ba5gS.gif).
I'm working on something unrelated for a couple of days, and will be able to test this in situ soon, but not now. Sorry. But I totally trust you. Moreover, you have at least one test case, and the bug is pretty simple to check if resolved

Thanks again, and 🍻 cheers!

**Comment by satanTime** [comment]
Ahaha, thanks :) 

Sure, no rush here, I have the same feelings that the issue has been fixed. Just need an extra proof once you have time.

Thanks in advance and happy coding!

**Comment by satanTime** [comment]
[v11.3.1](https://github.com/ike18t/ng-mocks/releases/tag/v11.3.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by GerkinDev** [comment]
Hi again,

I can confirm this works in my real-life situation ! :tada:

Thank you so much, happy new year ! :tada::tada::tada:
