### ISSUE TITLE
Feature Request: Allow ng-mocks to work with standalone components

### ISSUE THREAD

**Issue by DmitryEfimenko** [ike18t/ng-mocks#2687]
### Describe the feature or problem you'd like to solve

Angular v14 is released and the standalone components are now available.
We need support for mocking of standalone component dependencies (anything that's inside of the `imports` property of the `@Component` decorator).

### Proposed solution

It appears we should consider the standalone components affect existing APIs in the ng-mocks:
1. MockComponent
2. MockBuilder

The following discussion will use `MyStandaloneComponent` as defined below:

```ts
@Component({
  standalone: true,
  imports: [CoolModule, FooComponent, BarDirective, BazPipe],
  template: `I'm a standalone component!`
})
export class MyStandaloneComponent {}
```

#### 1. MockComponent

I think `MockComponent(MyStandaloneComponent)` should behave exactly like it used to - the component should be mocked. However, in addition, all the members of the `imports` property should also be mocked

#### 2. MockBuilder

`MockBuilder(MyStandaloneComponent)` should keep the implementation of the `MyStandaloneComponent` itself. However, all the dependencies specified in the `imports` property should be mocked.
This would go well with the best practices of "shallow" component testing. If there's a need to "keep" one of the dependency of the `MyStandaloneComponent`, the developer can leverage the existing `.keep(BarDirective)` functionality.

### Additional context

* [RFC: Standalone components, directives and pipes - making Angular's NgModules optional](https://github.com/angular/angular/discussions/43784)
* [Testing a standalone component using the Angular testbed](https://this-is-angular.github.io/angular-guides/docs/standalone-apis/testing-a-standalone-component-using-the-angular-testbed)

**Comment by DmitryEfimenko** [comment]
FYI, before working on this issue we might want to see how this [open issue in Angular](https://github.com/angular/angular/issues/46110) will unwrap.

**Comment by satanTime** [comment]
Agree, makes sense.

Is it a syntax sugar for a module with single export?

```ts
@NgModule({
  imports: [CoolModule, FooComponent, BarDirective, BazPipe],
  declarations: [MyStandaloneComponent],
  exports: [MyStandaloneComponent]
})
class StandaloneComponentModule {}
```

Sorry, I haven't code with angular for a year already and missed this feature :)

I'm asking, because it looks simpler to convert it like that in `MockBuilder`.
In `MockComponent`, I can simply remove all imports, just need to check if they are available in nested components.

**Comment by DmitryEfimenko** [comment]
yeah, I think that's pretty much it. I believe it's not quite 1:1 comparison. There are some nuances, but for the purposes of unit testing I don't think these nuances are important.

**Comment by Dominik-Kriese** [comment]
Hi,

just to push this topic a little:

I use ng-mocks a lot in conjunction with jests snapshot testing feature to reduce the bloat of rendered Angular Material Components as well as predictable false negatives in my test suite. Would love to use standalone components there, but i don't as the drawbacks in testing are to high for me at the moment.

PS: tanks for this awesome lib, it helps a lot and speeds up things by quite a margin :)

**Comment by satanTime** [comment]
After some research:

Anything imported in a standalone declaration cannot be used anywhere else. The exception is services. They are available in parent declarations.

So if we mock a standalone declaration, it should simply provide provides from all imported modules.

**Comment by satanTime** [comment]
Hi @DmitryEfimenko, could you I ask you test current implementation?

[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/8921010/ng-mocks.zip)

Now it keeps the component and mocks its imports if the component is standalone. You can keep, exclude etc:
```ts
// It does mock imports
MockBuilder(StandaloneComponent).keep(ImportedPipe);
```

if you want to keep its imports too, then you need to add its config separately or use chain methods:
```ts
// It doesn't mock imports
MockBuilder(StandaloneComponent).keep(StandaloneComponent, {standalone: false});

// It doesn't mock imports
MockBuilder().keep(StandaloneComponent);
```

**Comment by DmitryEfimenko** [comment]
I don't quite have a playground for standalone components set up yet, but I'll get it going and give it a spin. Thanks!

**Comment by satanTime** [comment]
Ah, oki then. It should do the job :) I'm waiting for `primeng` update to support A14 and will release the next major version of `ng-mocks`.

**Comment by satanTime** [comment]
Ah, also forgot.

@Dominik-Kriese, if you have standalone things in your project, could you give a try to the latest updates: [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/8921010/ng-mocks.zip)?

Thank you in advance!

**Comment by Dominik-Kriese** [comment]
@satanTime I only had very small and dumb components as standalone components due to the risks of low test coverage, but those seem to work fine with the new updates provided by you :)

**Comment by satanTime** [comment]
Great. Thanks. 

Let's hope primeng will be released soon.

**Comment by DmitryEfimenko** [comment]
you've mentioned `primeng` a couple times. I'm curious, why ng-mocks release is waiting for the release of primeng? What's the relationship?

**Comment by satanTime** [comment]
It's a historical thing from the times when CI ran only 4 parallel jobs. To reduce the time for ensuring that e2e tests with 3rd-party libs work correctly, node_modules for the lib and e2e is shared and therefore depends on all all 3rd-party libraries.

Now, it's possible to add one more CI step to install node_modules separately for e2e tests.
However, I hope `primeng` will be faster than my patience and I won't need to do anything, only wait :)

**Comment by satanTime** [comment]
[v14.0.0](https://github.com/ike18t/ng-mocks/releases/tag/v14.0.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by vzakharov-rxnt** [comment]
ng-mocks does not work with standalone components in 2025. Getting an error like:
```
Error: Unexpected "MockOfDxiButtonComponent" found in the "declarations" array of the "MockOfDxiButtonModule" NgModule, "MockOfDxiButtonComponent" is marked as standalone and can't be declared in any NgModule - did you intend to import it instead (by adding it to the "imports" array)?
```
DxiButtonComponent is a transitive dependendecy. The app works fine in prod, but getting the above error in test.
