### ISSUE TITLE
Currently there's no way to access passed data as @ContentChild in mocked component.

### ISSUE THREAD

**Issue by Michael-Gusev** [ike18t/ng-mocks#27]
Hey.

I use `@ContentChild` in my components and found if I want to mock it, then I can't inspect how passed blocks were rendered. There's support for `ng-content`, but nothing for `template`.
 
In test you can find an example of what I mean.
Please review changes there: https://github.com/ike18t/ng-mocks/pull/26.

**Comment by ike18t** [comment]
Thanks for contributing! I have just released your changes.

**Comment by Michael-Gusev** [comment]
Thanks!
