### ISSUE TITLE
MockService with ngMocks.stub vs. MockProvider overrides vs. MockInstance vs. ngMocks.defaultMock

### ISSUE THREAD

**Issue by krema** [ike18t/ng-mocks#270]
Hi, 

Thank you for that handy library. I am trying to mock a service and make the properties and method configurable for each test. 

The documentation gives us several ways to accomplish this. Unfortunately I am a little bit confused by all these possibilities. It took me some time to figure this out. Would it be useful if we add a section in the readme describing the different ways how to use them, what they do and for which use case we need them?

1. MockService with ngMocks.stub
```
const myServiceMock = MockService(MyService);
MockProvider(MyService, myServiceMock);

it('test', () => {
  ngMocks.stub(myServiceMock , {
    method: jasmine.createSpy(),
    subject$: EMPTY,
  });
});
```

2. MockProvider override
```
MockProvider(MyService, {
    method: jasmine.createSpy(),
    subject$: EMPTY,
    })

it('test', () => {});
```

3. MockInstance
```
MockProvider(MyService)

it('test', () => {
  MockInstance(MyService, () => ({
    method: jasmine.createSpy(),
    subject$: EMPTY,
  })),
});
```

3. defaultMock
```
ngMocks.defaultMock(MyService, () => ({
    method: jasmine.createSpy(),
    subject$: EMPTY,
}));

MockProvider(MyService)

it('test', () => {});
```

**Comment by satanTime** [comment]
Hi @krema,

thanks for the suggestion, I'll add a section to the readme about that.

**Comment by satanTime** [comment]
Hi @krema,

I've rewritten the section. Looking forward to your feedback: https://github.com/satanTime/ng-mocks/tree/issues/270#how-to-mock-services

**Comment by krema** [comment]
Hi @satanTime,

Thanks for the revision and clarification. It is clearer to me now. 

When I look at my projects where I use ngMocks I mostly use it for mocking components, pipes and directives. Now for services I have different requirements. I have to stub/reconfigure the return values of the methods or properties of the mocked service differently for each test in a test suite. I thought it would be handy to use MockService for this as it comes with the auto-spy feature. 

Now I am still confused is why there is MockInstance when we have MockService. Maybe I still don't understand the details but the only difference between MockInstance and MockService is that MockInstance can only mock its methods and properties once before we call TestBed.get(). Once we call TestBed.get() we cannot reconfigure the return values, can we? I see it as a major disadvantages compared to MockService. 

Right now I am wondering if ngMocks offers any convenience for reconfiguring service mock methods and properties. Let me show you how I have been using it so far.  

```
describe("MockService", () => {
 const authServiceMock = MockService(AuthService);
  let service: MyService;

  beforeEach(() =>
    TestBed.configureTestingModule({
      providers: [
        { provide: AuthService, useValue: authServiceMock },
        MyService
      ]
    })
  );

  beforeEach(() =>
    service = TestBed.get(MyService);
  );

  it("first - isLogged in true", () => {
    ngMocks.stub(authServiceMock, () => ({
      isLoggedIn$: of(true),
    }));

    // act
    // assert
  });

  it("second - isLogged in false", () => {
    ngMocks.stub(authServiceMock, () => ({
      isLoggedIn$: of(false),
    }));

    // act
    // assert
  });
});
```

I would probably replace the MockInstance with MockService and rename it to MockInstance. I don't like the naming of MockService because I expect it to be for services only but we can actually mock any instance of a class. 

It would be very handy if we could have something like this:

```
describe("MockService", () => {
 const authServiceMock = MockInstance(AuthService);
  let service: MyService;

  beforeEach(() =>
    TestBed.configureTestingModule({
      providers: [
        MockProvider(AuthService, authServiceMock),
        MyService
      ]
    })
  );

  beforeEach(() =>
    service = TestBed.get(MyService);
  );

  it("first - isLogged in true", () => {
    authServiceMock.isLoggedIn$.and.returnValue(of(true))

    // act
    // assert
  });

  it("second - isLogged in false", () => {
    authServiceMock.isLoggedIn$.and.returnValue(of(false))

    // act
    // assert
  });
});
```

Can you maybe explain why there is MockInstance if we have MockService?
Thanks

**Comment by satanTime** [comment]
Hi @krema,

thanks for the detailed feedback, I'll investigate it later the next week and try to propose a solution.

About the last question.

The general difference between them is that:
- if you need to customize an instance of a component / directive / pipe / service / token - `MockInstance` should be the right choice, mostly right in `it`.
- If you need to get a mock object of a class such as `Window` or `Injector` (not component / directive / pipe / service / token) - `MockService` is the right choice.

You are right about the issue in names, unfortunately, it came with evolution of the library and purposes of the functions have been extended that opened different possibilities for their usage.
Once A12 is here, the name will be changed as a breaking changes.

**Comment by satanTime** [comment]
I think, what you are asking is doable without any adjustments.

```ts
import { Component, Injectable } from '@angular/core';
import { TestBed } from '@angular/core/testing';
import { MockProvider, MockRender } from 'ng-mocks';
import { Subject } from 'rxjs';

export const EMPTY = new Subject<any>();
EMPTY.complete();

@Injectable()
class TargetService {
  public stream$ = EMPTY;
}

@Component({
  selector: 'target',
  template: `{{ service.stream$ | async }}`,
})
class TargetComponent {
  public constructor(public readonly service: TargetService) {
  }
}

fdescribe('issue-270', () => {
  const stream$ = new Subject<number>(); // <- defining out stream control

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [TargetComponent],
      providers: [
        MockProvider(TargetService, {stream$}), // <- overriding the property in the mock TargetService
      ],
    });
  });

  it('mocks the property', () => {
    const fixture = MockRender(TargetComponent);

    // default template
    expect(fixture.nativeElement.innerHTML).toEqual('<target></target>');

    // emit 1
    stream$.next(1);
    fixture.detectChanges();
    expect(fixture.nativeElement.innerHTML).toEqual('<target>1</target>');

    // emit 2
    stream$.next(2);
    fixture.detectChanges();
    expect(fixture.nativeElement.innerHTML).toEqual('<target>2</target>');
  });
});
```

**Comment by satanTime** [comment]
In your case it might be like that:

```ts
describe("MockService", () => {
  const isLoggedIn$ = new Subject(); // <- just a subject
  let service: MyService;

  beforeEach(() =>
    TestBed.configureTestingModule({
      providers: [
        MockProvider(AuthService, {
          isLoggedIn$: () => isLoggedIn$, // passing the subject into the mock
        }),
        MyService,
      ]
    })
  );

  beforeEach(() =>
    service = TestBed.get(MyService);
  );

  it("first - isLogged in true", () => {
    isLoggedIn$.next(true); // <- emitting true

    // act
    // assert
  });

  it("second - isLogged in false", () => {
    isLoggedIn$.next(true); // <- emitting false

    // act
    // assert
  });
});
```

**Comment by satanTime** [comment]
[v11.4.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.4.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
