### ISSUE TITLE
Since version 11.1.0 ngmocks.stub doesn't work after TestBed has initialized

### ISSUE THREAD

**Issue by krema** [ike18t/ng-mocks#272]
I tried to upgrade ng-mocks from version 11.0.0 to the latest version but my existing tests failed. I tracked it down to version 11.1.0 (https://github.com/ike18t/ng-mocks/compare/v11.0.0...v11.1.0). 

The following test fails with version >= 11.1.0 because it doesn't allow me to override my stubs after the TestBed.get method has been called.

```
const authServiceMock = MockService(AuthService);

beforeEach(async(() => TestBed.configureTestingModule({
  providers: [
    MockProvider(AuthService, authServiceMock)
  ]
})));

it('test', () => {
  ngMocks.stub(authServiceMock, {
    isLoggedIn$: cold('a', { a: true }),
  });

  service = TestBed.get(MyService);

  ngMocks.stub(authServiceMock, {
    isLoggedIn$: cold('ab', { a: true, b: false }),
  });
});
```

I think the reason is following change:

https://github.com/ike18t/ng-mocks/compare/v11.0.0...v11.1.0#diff-89ddecf61a2d424a8dcc92b2c026270e77c96e56b1526a88e3d543c25dbd43f1R29-R39

Is it because from now on we always create an instance with useFactory?

**Comment by satanTime** [comment]
Hi, might you share how AuthService looks like?

I think I know the issue, it might be caused by flags in define properties calls.

**Comment by satanTime** [comment]
Ah, no, I think it's another issue.

Starting some version MockProvider extends the value, instead of using it. It was done to avoid huge calls on large services.

I think in your case you need to use `useValue` directly, because there is nothing to do for `MockProvider`.
```ts
beforeEach(async(() => TestBed.configureTestingModule({
  providers: [
    {provide: AuthService, useValue: authServiceMock},
  ]
})));
```

**Comment by krema** [comment]
AuthService is an example I created. In this example isLoggedIn$ is an Observable. My tests fail now because I do a lot (re)configuring/mocking properties and methods within the tests and for each test separately. Is there maybe other way to accomplish that?

**Comment by satanTime** [comment]
There is an example: https://codesandbox.io/s/gifted-chebyshev-778cq?file=/src/test.spec.ts

**Comment by satanTime** [comment]
But still... I don't get why it should work - if `MyService` depends on `AuthService` then change of the pointer to `isLoggedIn$` shouldn't have the effect anyways...

Might you provide a small test on codesandbox with the latest version of ng-mocks that fails due to the issue you have?

**Comment by krema** [comment]
https://codesandbox.io/s/practical-moser-3x05x?file=/src/test.spec.ts

**Comment by satanTime** [comment]
Yep, then right.

And sorry for the confusion and this breaking change, I hoped `MockProvider` wasn't used much when introduced it :)

Then, I think, nothing to do in this issue. Feel free to close it if nothing has left.

**Comment by krema** [comment]
Thanks for your help!
