### ISSUE TITLE
ControlValueAccessor Mock not working on MatInput

### ISSUE THREAD

**Issue by jensweigele** [ike18t/ng-mocks#305]
When having an input element like that:
```
<input data-testid="inputControl" matInput [formControl]="myControl" required>
```
with a test setup like that:
```
MockBuilder()
                .mock(MyModule)
                .keep(MyComponent)
                .keep(ReactiveFormsModule)
```
I can get a MatInput Mock Instance with:
```
ngMocks.get(ngMocks.find(['data-testid', 'inputControl']), MatInput)
```

But this mock is not a "MockControlValueAccessor" (isMockControlValueAccessor is false). I also tried other approaches but did not find a way to get it working. Ticket #73 is about a fix for that, but maybe this fix got lost by the refactoring between the version!?

- [x] test overrides of interfaces to ensure it is possible
- [x] Lazy instance on proxy should receive previous calls of proxy
- [x] ngMocks.touch, .change and so on

**Comment by satanTime** [comment]
Hi, thanks for the report! I'll take a look today.

Might you share how matInput has been imported?

Also is it really `.find`? `ngMocks.find(['data-testid', 'inputControl'])`, I would assume that it should be `.reveal`.

**Comment by satanTime** [comment]
Also is it on 11.7.0 or 11.8.0? there was a regression before: https://github.com/ike18t/ng-mocks/issues/302

**Comment by jensweigele** [comment]
MatInput is imported in "MyModule" via imports: [MatInputModule] (so I think that should be mocked).
But I also tried to use:
```
MockBuilder()
                .mock(MyModule)
                .keep(MyComponent)
                .keep(ReactiveFormsModule)
                .mock(MatInput)
```
(also with mock(MatInputModule)

>  Also is it really .find? ngMocks.find(['data-testid', 'inputControl']), I would assume that it should be .reveal.

Yes it's find. But it's interesting - the mock-helper.d.ts does not contain a reveal Method (11.7.0)
I just saw that you published a new version some hours again - let me doublecheck with that version.

**Comment by satanTime** [comment]
Ah true :) I forgot that it will be transformed to `[data-testid="inputControl"]`, sorry :) a too fresh feature. Good, then I'll investigate how it works on 11.7.0 and 11.8.0. The fix should be here next days and released on the weekend.

**Comment by jensweigele** [comment]
I've the same behavior with 11.8.0

**Comment by satanTime** [comment]
thanks, then I'll investigate what did I break again.

**Comment by satanTime** [comment]
So, the thing is that `MatInput` doesn't implement `ControlValueAccessor`.
Therefore, I would say that when `isMockControlValueAccessor` returns `false` it is expected.

What is the logic behind test?

Before all mock directives and components implemented `ControlValueAccessor`, but it was wrong, because it gives a false impression, how we can access real `ValueAccessor`. Therefore, to respect interfaces between a real instance and its mock a fix was added to apply `ControlValueAccessor` only if the original declaration implements it.

But still, let's discuss it, maybe I missed something.

**Comment by satanTime** [comment]
Ah, doesn't work in no-ivy. I think the best way would be to provide `ngMocks.touch(debugEl)` and `ngMocks.change(debugEl)`, so nobody needs to know what is under the hood and how control value accessor is set.

**Comment by satanTime** [comment]
Fixed.

Instead of calling `ngMocks.get(ngMocks.find(['data-testid', 'inputControl']), MatInput)` you can use now the next syntax:

```ts
const el = ngMocks.find(['data-testid', 'inputControl']);
ngMocks.change(el, 'desiredValue');
```

**Comment by satanTime** [comment]
[v11.9.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.9.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by jensweigele** [comment]
Thanks! Will give it a try this week
