### ISSUE TITLE
Add some basics helpers to ngMocks

### ISSUE THREAD

**Issue by kekel87** [ike18t/ng-mocks#310]
Hi, we've been using your lib since 2 years now and it's really changing our lives!

However, we need to use a small helper to perform very basic tasks during the tests.
We don't want to pull another lib just to get those basic helpers (like `ngneat/spectator`, etc).

It would be cool, if some of them could be integrated to your helper `ngMocks` (especially since there are already things in place).

Here is a short list of helper that, we believe, answer the vast majority of unit tests.

- Get a text of element(s)
```typescript
// Get text of an element 
ngMocks.text(fixture?, cssSelector)
ngMocks.text(debugElement?, cssSelector)
// Internal
// target.nativeElement.innerText

// Get text of many elements
ngMocks.allText(fixture?, cssSelector)
ngMocks.allText(debugElement?, cssSelector)
// Get text of many elements, but trim (~contains)
ngMocks.allTextTrim(fixture?, cssSelector)
ngMocks.allTextTrim(debugElement?, cssSelector)
```

-  Trigger events
```typescript
// Trigger event of target element
ngMocks.trigger(fixture?, cssSelector, eventName: string, eventObj: any = null)
ngMocks.trigger(debugElement?, cssSelector, eventName: string, eventObj: any = null) 

// Click on target element, often use
ngMocks.click(fixture?, cssSelector)
ngMocks.click(debugElement?, cssSelector)
```

- Get value of input
```typescript
ngMocks.input // Already done !!

// Get values of many inputs
ngMocks.allValue(fixture?, cssSelector)
ngMocks.allValue(debugElement?, cssSelector)
// Get values of many inputs, but trim (~contains)
ngMocks.allValueTrim(fixture?, cssSelector)
ngMocks.allValueTrim(debugElement?, cssSelector)
```

- Write in input and correctly trigger `@angular/material`:
```typescript
ngMocks.typeIn(fixture?, cssSelector, value: string)
ngMocks.typeIn(debugElement?, cssSelector, value: string)
ngMocks.typeIn(fixture?, cssSelector, value: string)

// Internal
// target.nativeElement.value = value;  
// target.triggerEventHandler('input', { target: target.nativeElement });  
// target.nativeElement.blur();
```

- Get component(s) or directive(s)
```typescript
ngMocks.findInstance // Already do the job !!
ngMocks.findInstances  // Already do the job !!

// But should be nice to add cssSelector
ngMocks.findInstance(cssSelector, Directive1)
ngMocks.findInstances(cssSelector, Directive1)
```

What do you think about it ?
Thanks

**Comment by satanTime** [comment]
Hi @kekel87, sure,

might you also add input and output to every example in order to demonstrate how data should be processed?

**Comment by kekel87** [comment]
Yep, here are some examples of usage :

- Get a text of element(s)
```html
<div>
  <span>Text 1</span>
  <span> Text 2</span>
  <span>Text 3 </span>
</div>
```
```typescript
// Get text of an element 
ngMocks.text('div span') // return 'Text 1'
// Usage :
expect(ngMocks.text('div span')).toContain('Text 1')

// With debugElement (this example work for all debugElement? input)
const span = ngMocks.find('div span')
ngMocks.text(div) // return 'Text 1'

const div = ngMocks.find('div')
ngMocks.text(div, 'span') // return 'Text 1'

// With another fixture (default current) (this example work for all fixture? input)
const fixture = MockRender(AnotherComponent);
ngMocks.text(fixture, 'div span') // return 'Text 1'

// Get text of many elements
ngMocks.allText('div span') // Return ['Text 1', ' Text 2', 'Text 3 ']
// Usage :
expect(ngMocks.allText('div span') ).toEqual(['Text 1', ' Text 2', 'Text 3 '])

// Get text of many elements, but trim (~toContain)
ngMocks.allTextTrim('div span') // Return ['Text 1', 'Text 2', 'Text 3']
// Usage :
expect(ngMocks.allText('div span') ).toEqual(['Text 1', 'Text 2', 'Text 3'])
```

-  Trigger events
```html
<div>
  <button (click)="someFunct()"></button>
  <custom (customEvent)="someFunct($event.data)"></custom>
</div>
```
```typescript
// Trigger event of target element
ngMocks.trigger('custom', 'customEvent') // void
ngMocks.trigger('custom', 'customEvent', { data: 'a data' }) // void
ngMocks.trigger('button', 'click') // void
// Usage :
ngMocks.trigger('custom', 'customEvent', { data: 'a data' });
expect(intenralInSomeFunct).toHaveBeenCalledWith('a data');

// Click on target element, often use
ngMocks.click('button') // void
// Usage :
ngMocks.click('button');
expect(intenralInSomeFunct).toHaveBeenCalled();
```

- Get value of input
```html
<div>
   <input type="text" value="Value 1">
   <input type="text" value=" Value 2">
   <input type="text" value="Value 3" >
</div>
```
```typescript
ngMocks.input // Already done: https://ng-mocks.sudo.eu/api/ngMocks/input
// Maybe make `debugElement` optional like other helper

// Get values of many inputs
ngMocks.allValue('div input') // return ['Value 1', ' Value 2', 'Value 3 ']
// Usage :
expect(ngMocks.allValue('div span') ).toEqual(['Value 1', ' Value 2', 'Value 3 '])

// Get values of many inputs, but trim (~toContain)
ngMocks.allValueTrim('div input') // return ['Value 1', ' Value 2', 'Value 3 ']
// Usage :
expect(ngMocks.allValueTrim('div span') ).toEqual(['Value 1', 'Value 2', 'Value 3'])
```

- Write in input and correctly trigger `@angular/material`:
```html
<div>
   <input type="text"(input)="someFunc($event)">
</div>
```
```typescript
ngMocks.typeIn('div input', 'Hello there') // void
// Usage :
ngMocks.typeIn('div input', 'Hello there') // void
expect(ngMocks.input('div input')).toContain('Hello there')
expect(intenralInSomeFunct).toHaveBeenCalledWith('Hello there');
```

- Get component(s) or directive(s)
```html
<div>
   <h1 [routerLink]="['/']">Hello</h1>
   <a [routerLink]="['/', 'route']">there</a>
</div>
```
```typescript
// Already done: https://ng-mocks.sudo.eu/api/ngMocks/findInstance

// But should be nice to allow cssSelector
ngMocks.findInstance('div h1', RouterLink) // return routerLink directive at this selector
ngMocks.findInstances('div a', RouterLinkWithHref)// return routerLink directive at this selector
// Usage:
expect(ngMocks.findInstance('div h1', RouterLink).routerLink).toEqual(['/']);
expect(ngMocks.findInstance('div a', RouterLinkWithHref).routerLink).toEqual(['/', 'route']);
```

I can try to write the function signatures if you want.

**Comment by satanTime** [comment]
Hi again, thanks for the details. I'll take a look deeper on the weekend and provide you feedback.

Usually for such things, I add own helper functions beside `test.ts`, I think you to do the same. Anyway, I'll take a look at the proposal and try to estimate how much it fits the lib.

**Comment by satanTime** [comment]
Hi there,

I've checked proposed features.

Definitely, some of them make sense. The only this I would prefer to avoid personally is multiple responsibilities, in order to follow KISS and SOLID.

For example, to **find** an element, then **extract** its text and then **trim** every text node, sounds to me like 3 different function calls, whereas I understand how simple and useful it is to call 1 function instead.

Therefore, for now, I would suggest having **own helper file** which contains such helper functions.

## ngMocks.text ngMocks.allText ngMocks.allTextTrim

There is [`ngMocks.formatHtml`](https://ng-mocks.sudo.eu/api/ngMocks/formatHtml), and I've seen that in `jest` `innerText` doesn't work. At least, for me its value was always empty.

Therefore, to add a helper to get only formatted text makes sense.

But, responsibility how to find related `debugElements` and `debugNodes`, I would suggest to keep outside of this function.

Own helpers can be like that

```typescript
const text = selector => ngMocks.formatText(ngMocks.find(selector));

expect(text('div span')).toEqual('Text 1');
```

```typescript
const allText = selector => ngMocks.findAll(selector).map(ngMocks.formatText);

expect(allText('div span')).toEqual(['Text 1', 'Text 2', 'Text 3']);
```

```typescript
const allTextTrim = selector => ngMocks.findAll(selector)
  .map(ngMocks.formatText)
  .map(v => v.trim());

expect(allText('div span')).toEqual(['Text 1', 'Text 2', 'Text 3']);
```

Idea behind own helper function is that someone may want to lowercase / uppercase text or remove all spaces etc. And to cover all possible cases in `ng-mocks` can end up with lots of helpers which might be complicated to maintain. 

## ngMocks.trigger ngMocks.click

Might you explain how it differs from built-in [`triggerEventHandler`](https://angular.io/api/core/DebugElement#triggerEventHandler)?

```ts
const trigger = (selector, event, payload?) => ngMocks.find(selector). triggerEventHandler(event, payload);

trigger('button', 'click');
```

## ngMocks.value ngMocks.allValue ngMocks.allValueTrim

I would go for own helper function with a chain of `.map`.

## ngMocks.typeIn

This one is interesting. Usually, I simply rely on a mock `ControlValueAccessor` interface and call its functions. However, I saw the approach you described.

Might you create a min example on stackblitz to demonstrate desired behavior of a mock declaration and `@angular/material`?

## css selectors where they are possible

Css selectors in all functions - agree, makes sense, I'll check where it is missing and add it.

**Comment by kekel87** [comment]
Hi,

I understand what you mean about the responsibilities and the fact that it is difficult to maintain.

All those little functions you suggest, we already do, but when we change projects/missions/clients often, it's hard to keep track of them. But `ng-mocks` are easy to follow, that's why I proposed to integrate them.

The idea was to identify the most useful helpers to avoid having to copy/paste them between our different projects.

I am trying to find a solution to this problem.

## ngMocks.text ngMocks.allText ngMocks.allTextTrim

I like the principle of `ngMocks.formatText` and `.map` chaining.

## ngMocks.trigger ngMocks.click

There are no differences. It's just a shorter/readable syntax:
```typescript
if('should call internal function', () => {
	ngMocks.find('button').triggerEventHandler('click', { data: 'data' ]);
	expect(intenralInSomeFunct).toHaveBeenCalledWith('data');
});
```
```typescript
if('should call internal function', () => {
	ngMocks.trigger('button', 'click', { data: 'data' ]);
	expect(intenralInSomeFunct).toHaveBeenCalledWith('data');
});
```
```typescript
if('should call internal function', () => {
	ngMocks.click('button', { data: 'data' ]);
	expect(intenralInSomeFunct).toHaveBeenCalledWith('data');
});
```

## ngMocks.value ngMocks.allValue ngMocks.allValueTrim

Ok

## ngMocks.typeIn

After thinking about it, I think the `triggerEventHandler` and [`isMockControlValueAccessor`](https://ng-mocks.sudo.eu/api/helpers/isMockControlValueAccessor) will cover all cases. Sorry ...

## css selectors where they are possible

Perfect.

**Comment by satanTime** [comment]
about `isMockControlValueAccessor`, there is a new feature [`ngMocks.change`](https://ng-mocks.sudo.eu/api/ngMocks/change) which is even simpler.

But I'm really curious and that `blur` call. Is it required for material design?

**Comment by kekel87** [comment]
I don't know if it's still in use. I think it dates back to the time when we didn't mock [material](https://github.com/angular/components/blob/master/src/material/input/input.ts#L345). To trigger the change of value and put the input in the same state as if we had done it manually.

**Comment by satanTime** [comment]
I've created separate issues for every case. This issue will be closed, feel free to subscribe there and leave comments.
