### ISSUE TITLE
ng-mocks with Jest - coverage report

### ISSUE THREAD

**Issue by Carsten750** [ike18t/ng-mocks#311]
Great tool! Works very well.

We use ng-mocks with Jest. Jest provides a lot of great possibilities: snapshot testing, many additional matchers etc.

But there is maybe one small imperfection. Mocked components show up in the coverage report. Is there any way to stop this?

That would be great!

Thanks a lot!
Carsten

**Comment by satanTime** [comment]
Hi,

thanks for the report. Might you provide a simple repo with the issue?

Also might you explain the idea to hide them a bit deeper?

I would assume that this behavior is expected. If there are 2 components in an app, and tests have been written only for one of them, then the second one has 0 coverage because of zero own tests. In the same time, because there is the dependency between components - both of them should be imported in tests and both of them will be present in the coverage report.

If you want to exclude these components on a purpose, I would go for something like https://jestjs.io/docs/configuration#coveragepathignorepatterns-arraystring

**Comment by Carsten750** [comment]
Test:
`
@Component({
  selector: 'my-panel-container',
  template: ` <layout-panel>Content</layout-panel> `
})
class MyTestComponent {}


describe('The LayoutPanel,', () => {
  let component: MyTestComponent;
  let fixture: ComponentFixture<MyTestComponent>;

  beforeEach(async(() => {
    TestBed.configureTestingModule({
      declarations: [
        LayoutPanel,
        MyTestComponent,
        ...MockComponents(QdTabComponent)
      ]
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(MyTestComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  test('matched the snapshot.', () => {
    expect(fixture.nativeElement).toMatchSnapshot();
  });
});
`

**Comment by satanTime** [comment]
Works for me correctly. When I run all tests I get 100%, when I run partially - I get partial coverage.

<img width="1290" alt="a11+%E2%80%93+layout-panel component spec ts+2021-03-15+22-08-30" src="https://user-images.githubusercontent.com/966305/111221724-292bcb00-85db-11eb-9175-41a7f22d1771.png">

```
> jest -w 1 --config jest.es5ivy.js "--collect-coverage"

 PASS  src/app/to-mock.component.spec.ts
 PASS  src/app/layout-panel.component.spec.ts
---------------------------|---------|----------|---------|---------|-------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------------|---------|----------|---------|---------|-------------------
All files                  |     100 |      100 |     100 |     100 |
 layout-panel.component.ts |     100 |      100 |     100 |     100 |
 to-mock.component.ts      |     100 |      100 |     100 |     100 |
---------------------------|---------|----------|---------|---------|-------------------

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        3.223 s
Ran all test suites.
```

**Comment by satanTime** [comment]
Hi @Carsten750, 

any update on this?

**Comment by satanTime** [comment]
Hi @Carsten750,

I'm going to close the issue. I think, the case you need is covered in my previous comment.
Feel free, to drop a comment if we should discuss it further.

Happy coding!
