### ISSUE TITLE
An additional element is being created for ng-container

### ISSUE THREAD

**Issue by michaeljota** [ike18t/ng-mocks#32]
Seems like an issue introduced with #26. In `v6.2.3` when I mocked an element that had `ng-container` elements, that element was not being render, but as `v7.1.1`, that element is creating a `div[data-key="ng-content"]` before the content of the container.

This is making my template test fail, because the template now have this additional element that is actually not available in runtime, so is a test only element.

**Comment by ike18t** [comment]
I agree that those elements are unnecessary. It should be pretty easy to remove them and update the tests if you're interested in submitting a PR.

**Comment by ike18t** [comment]
@Michael-Gusev Is there any reason that you can see not remove this?

**Comment by Michael-Gusev** [comment]
Hi everybody.
The thing is that we can pass not only content, but also predefined templates.
Example how it can be passed: https://github.com/ike18t/ng-mocks/blob/master/lib/mock-component/mock-component.spec.ts#L27-L32
Example how it can be rendered: https://github.com/ike18t/ng-mocks/blob/master/lib/mock-component/test-components/template-outlet.component.ts#L6-L9

In my tests I usually assert that I sent right html to ng-content and another html to templates.
To separate them in `debugElement(By.css())` for assertion I added `div` wrapper with `data-key` attribute for every type of injection, so we can query them separately.

I would say mocked component should provide an interface to get passed data (like `debugElement(By.css("[data-key='ng-content']"))` or `debugElement(By.css("[data-key='title']"))`), but it shouldn't render it exactly as original component.
It's like with `inputs` or `outputs` in mocked component - we can set them and get them, but they don't behave the same as in original component.

@michaeljota, might you give me an example of your component, its test and on which assert it fails? I'll play later today with `ng-content data-key="..."` to find a way to wrap passed html in invisible element, so it'll be rendered without wrapper, but not sure if it's possible.

**Comment by Michael-Gusev** [comment]
I would recommend to update assertions to use result of `debugElement(By.css("app-some-mocked-component[data-key='ng-content']"))`, instead of debugElement(By.css("app-some-mocked-component")).

**Comment by michaeljota** [comment]
@Michael-Gusev I'm using Jest, and `toMatchSnapshot`. You can read more here [Snapshot Testing](https://jestjs.io/docs/en/snapshot-testing)

**Comment by Michael-Gusev** [comment]
@michaeljota, thanks for the info. Could you give me an example of test which fails? For example on https://stackblitz.com.

**Comment by Michael-Gusev** [comment]
I think I found way how to don't add wrapper on empty ng-content or template.
PR will be done this week, hope today.

**Comment by michaeljota** [comment]
@Michael-Gusev https://stackblitz.com/edit/jest-angula-div-report?file=src/app/app.component.html

All the `ng-container`s a being replaced with that div.

**Comment by Michael-Gusev** [comment]
but it's mocked component, why do you expect it to be rendered as you original component?

**Comment by michaeljota** [comment]
That's a good questing. I'm mocking some of the components that my component needs, but I'm not actually mocking the component that I'm having trouble with.

I can't reproduce my original file here, but I'll try to make something that resembles it.

```ts
@Componet({
  selector: 'my-a'
  template: `I'm a component`
})
export class AComponent {}

@Component({template: `<my-a></my-a><ng-container *ngIf="true">I should not have a wrapper element</ng-container>`
export class BComponent {}

describe('BComponent'){
  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        BComponent,
        MockComponent(AComponent)
      ]
  })

  it('should not have a wrapper element', () => {
    const wrapperEl = fixture.debugElement.query('div[data-key="ng-content"]')
    expect(wrapperEl).toBeNull(); // Would fail, because a div[data-key="ng-content"] is being created
  });
}

**Comment by Michael-Gusev** [comment]
Aha, so in our case mocked component doesn't accept any nested html as `ng-content` or `ng-template`.

As an option I can add logic if there's no injected `ContentChild` templates - then to render `ng-content` without any wrapper, because we can fetch it as `By.css('my-a')`.
It should solve the issue.
But once we have some `ContentChild`, then everything will be rendered inside of wrapper.
I'll try to find way to add condition to don't render wrapper if its content is empty.

@ike18t, what do you think?

**Comment by Michael-Gusev** [comment]
also `expect(wrapperEl).toBeNull()` has to fail anyway. It's mocked component which has own rules of render.

**Comment by michaeljota** [comment]
@Michael-Gusev 
> also expect(wrapperEl).toBeNull() has to fail anyway. It's mocked component which has own rules of render.

I wasn't being created before, so I don't think it should be created now.

**Comment by Michael-Gusev** [comment]
@michaeljota, might you try https://github.com/ike18t/ng-mocks/pull/33 and let us know how it works for you?

Thanks.

**Comment by Michael-Gusev** [comment]
> @Michael-Gusev
> 
> > also expect(wrapperEl).toBeNull() has to fail anyway. It's mocked component which has own rules of render.
> 
> I wasn't being created before, so I don't think it should be created now.

because before ng-mocks didn't support mock of ContentChild properties.

**Comment by ike18t** [comment]
@michaeljota Did you get a chance to checkout the PR that @Michael-Gusev made?

**Comment by ike18t** [comment]
No worries. @Michael-Gusev How confident are you that this resolves @michaeljota 's problem?

**Comment by Michael-Gusev** [comment]
:) very good question. I would say if he doesn’t use Child decorator it should solve the issue. If he does, then it’s not possible to fix it due to wrappers we need to separate Ng-content from injected Ng-templates.

**Comment by michaeljota** [comment]
I think I'm not. 👍

**Comment by ike18t** [comment]
Hey @michaeljota , I'm going to go ahead and close this card but feel free to reopen it if you continue to experience the issue.
