### ISSUE TITLE
MockModule does not work for MatSelectModule in 9.6.4

### ISSUE THREAD

**Issue by ngfx** [ike18t/ng-mocks#329]
ng-mocks version: 9.6.4.
angular material version: 9.2.4

When mocking the **mat-select** component in unit test, I did **MockModule(MatSelectModule)**, and it causes the unit tests to fail with error "**No value accessor for from control with name 'xxx'**".

The component template was like:
`
<mat-form-field>
    <mat-select formControlName="xxx">...</mat-select>
</mat-form-field>
`

The behavior was OK in ng-mocks 9.5.0. Do not know what has changed since then.

**Comment by satanTime** [comment]
Hi, thanks for the report.

could you try the latest version?

**Comment by ngfx** [comment]
For my project, I am still using Angular 9, so I tried with your latest 9.x.x version. Even if the latest 11.x.x version had fixed it, I am not going to upgrade in a while before the upgrade of Angular. So I do hope you can have a fix release for the version 9 if you confirm this issue. Thanks.

**Comment by satanTime** [comment]
There is no link between angular and ng-mocks version. You can use any on any.

**Comment by ngfx** [comment]
ok good to know it, thanks. I will have a try with the latest version 11.

**Comment by ngfx** [comment]
The latest version 11 seems to be Good! Thanks. Although still don't know the cause of this issue in the early version.

**Comment by satanTime** [comment]
I'm quite sure, I broke something that time. There were many changes regarding control value accessor lately.

Then I'll close the issue for now. Feel free to reopen it if something is still wrong.

Happy coding!
