### ISSUE TITLE
.keep(ReactiveFormsModule) causes FormBuilder to malfunction

### ISSUE THREAD

**Issue by garrappachc** [ike18t/ng-mocks#377]
Let's say I have a decently simple component that uses the `FormBuilder`:

```ts
@Component({
  selector: 'app-form',
  templateUrl: './form.component.html',
  styleUrls: ['./form.component.css']
})
export class FormComponent {

  form = this.fb.group({
    name: [],
  });

  constructor(
    private fb: FormBuilder,
  ) { }

}
```

```html
<form [formGroup]="form">
  <input type="text" formGroupName="name">
</form>
```

When I test it with ngMocks, like that:

```ts
describe('FormComponent with ngMocks', () => {
  let component: FormComponent;
  let fixture: MockedComponentFixture<FormComponent>;

  beforeEach(() => MockBuilder(FormComponent).keep(ReactiveFormsModule));

  beforeEach(() => {
    fixture = MockRender(FormComponent);
    component = fixture.point.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
```

the injected `FormBuilder` instance spits out undefined value, causing angular to fail the unit test:

    Error: formGroup expects a FormGroup instance. Please pass one in.

               Example:

               
            <div [formGroup]="myGroup">
              <input formControlName="firstName">
            </div>

            In your class:

            this.myGroup = new FormGroup({
               firstName: new FormControl()
            });

This error is thrown because the value of `form` is undefined.

I have uploaded a sample repo that reproduces this error: https://github.com/garrappachc/ng-mocks-reactive-forms-bug
In `form.component.spec.ts` you can see two unit tests - one that works (without using ngMocks) and one that doesn't.

Also, I am not sure when was this error introduced, all I know is that Angular version 11.2.5 was working fine and 11.2.6 started to cause the issue - but Angular itself is fine.

Here's my Angular version bump pr that started failing: https://github.com/tf2pickup-org/client/pull/803

**Comment by satanTime** [comment]
Hi, thanks for the report.

Yep. Sorry. My bad. I implemented some wrong changes around 11.2.6. 

Could update to the latest version of ng-mocks? It shouldn't have the issue.

**Comment by satanTime** [comment]
Ah okay. You mean Angular itself.

Then I'll dig into the issue next days and try to provide a fix ASAP.

**Comment by satanTime** [comment]
For now, I would say, that Angular fixed the issue they had. 

In a mock component, the `form` is `undefined`. However, `ReactiveFormsModule` hasn't been mocked. Therefore `[formGroup]="form"` is the same as `[formGroup]="undefined"` and I would expect it to fail.

A mix of mock components and real `FormsModule` or `ReactiveFormsModule` always has some tricky issues.

Might you describe, why you need to keep `ReactiveFormsModule`?
I would suggest to either keep both of the things or to mock both of them.

**Comment by garrappachc** [comment]
I do not want to mock either of them, `FormsModule` is not needed at all - take a look at the repo I created, in app.module.ts the only imports are `BrowserModule` and `ReactiveFormsModule`.

You are right saying that the Angular test fails because form is undefined, the problem is it should be defined.

```ts
 form = this.fb.group({
    name: [],
  });
```

Here, `form` should not be undefined.

**Comment by satanTime** [comment]
Yep `ReactiveFormsModule` imports `FormsModule` itself, that's only what I meant.

Good, then I'll dig into it later today / tomorrow.

**Comment by satanTime** [comment]
Hi, found the issue. `ng-mocks` didn't detect that `FormBuilder` is provided via `ReactiveFormsModule` and mocks it, which breaks the behavior.

The fix will take one week more.

A workaround is to keep `FormBuilder` too: `MockBuilder(FormComponent).keep(ReactiveFormsModule).keep(FormBuilder)`.

Sorry for the delay.

**Comment by satanTime** [comment]
This is the change: https://github.com/angular/angular/commit/b93fb79839f7d3532f6f81c5a273674d05b72831

`FormBuilder` isn't more provided via `ReactiveFormsModule` and has a new feature like `@Injectable({providedIn: ReactiveFormsModule})`

**Comment by satanTime** [comment]
Hi @garrappachc,

could you confirm that the new version works well for you? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6298682/ng-mocks.zip)

**Comment by garrappachc** [comment]
It works like a charm :)
Thank you for all your work!

**Comment by satanTime** [comment]
[v11.10.1](https://github.com/ike18t/ng-mocks/releases/tag/v11.10.1) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Simon-Hayden-iteratec** [comment]
Hi, I'm in the process of updating our repo to Angular 15 with ng-mocks 14.6.0 and I got the same error as described above.

Previously we just added `.keep(ReactiveFormsModule)` to use the `FormBuilder`/`NonNullableFormBuilder`, but after the upgrade I have to change everything to `.keep(NonNullableFormBuilder)`. Not the biggest deal, but it looks like this is an regression then?

**Comment by satanTime** [comment]
Hi @Simon-Hayden-iteratec,

right, this came from Angular updates. They started to make all module providers root providers to have better visibility in tree-shaking, because of that `FormBuilder` doesn't have a reference to `ReactiveFormsModule` and `FormsModule` anymore and there is no way to detect whether it should be kept or mocked.

I've covered that in FAQ: https://ng-mocks.sudo.eu/troubleshooting/faq#error-ng01052-formgroup-expects-a-formgroup-instance-please-pass-one-in

My recommendation is to add `.keep(NG_MOCKS_ROOT_PROVIDERS)`, also, it will be default in `ng-mocks@15`: https://github.com/help-me-mom/ng-mocks/issues/4701

**Comment by Simon-Hayden-iteratec** [comment]
Ah, thanks a lot! Sorry for not finding the FAQ :)
