### ISSUE TITLE
Issue with Animations Library

### ISSUE THREAD

**Issue by BuddyLReno** [ike18t/ng-mocks#42]
I'm building a project using Ionic v3 and I'm trying to write tests for some code in my Tabs page.  To do this I have to mock the page components. 

```
TestBed.configureTestingModule({
      declarations: [
        TabsPage,
        MiniPlayerStubComponent,
        MockComponent(ShowsPage)
      ],
```

When I do this, I started getting the error: `Cannot find module '@angular/animations'`.  I don't even use that but all my googling suggested I needed to import it. I did that and now when I run my test, I get this issue:

`TypeError: Cannot read property 'annotations' of undefined`.  

```
at MockDirectiveResolver.Object.<anonymous>.DirectiveResolver.resolve (node_modules/@angular/compiler/@angular/compiler.es5.js:14349:56)
      at MockDirectiveResolver.Object.<anonymous>.MockDirectiveResolver.resolve (packages/compiler/testing/src/directive_resolver_mock.ts:49:1)
      at Object.MockComponent (node_modules/ng-mocks/lib/mock-component/mock-component.ts:24:9)
```

This happens when the mock component tries to mock my ShowsPage.  It looks like it happens when it tries to reflect the class.  I'm not sure how to get past the error at this point, especially because this animations thing is not even something I use. I didn't have to import it until I needed to try mocking this page for testing.

Any help is super appreciated!

**Comment by satanTime** [comment]
I’ll take a look on week. Seems caused by my changes.

**Comment by satanTime** [comment]
Hi @BuddyLReno, could you try latest version of the package?

**Comment by ike18t** [comment]
I'm going to go ahead and close this issue since we haven't heard back. @BuddyLReno feel free to reopen it if your issue is not resolved.
