### ISSUE TITLE
Issues with `ChildContent` using attribute selector

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#445]
So, it's me again. I'm having problems to mock component using `ContentChild` selected by attribute. Here is the demo: https://stackblitz.com/edit/ng-mocks-examples-mp9pgs?file=app/app.spec.ts

Related to #68

Thank you so much for your work. And, do you have a patreon or something so that I can buy you a beer ? :beers:

**Comment by satanTime** [comment]
Thanks for the report! 

About beer, thanks, it would be nice. The next task is to configure patreon 🤣

**Comment by satanTime** [comment]
Hi there,

Might I ask whether `@ContentChild('[someAttribute]')` works in real code?

When I was testing it, for me it works only `@ContentChild('idOfElement')` for elements like `<div #idOfElement ></div>`, when I tried with tag names or attributes - the property is always `undefined`.

Another thing is that such mock components require `CommonModule` to be provided in `TestBed`, it has been fixed, but the legacy implementation still needs it.

Working on the fix to avoid failures in tests.

**Comment by GerkinDev** [comment]
NVM, this explains a lot of things actually  :sweat_smile:

**Comment by satanTime** [comment]
Yeah, but please wait with closing it. I added a fix to avoid runtime failures in such cases.

**Comment by satanTime** [comment]
[v11.11.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.11.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by satanTime** [comment]
Hi @GerkinDev,

how is life? I hope everything is fine on your side.

It took a while, and finally I've finished the process of verification and can officially accept beer donations: https://github.com/sponsors/satanTime.

**Comment by GerkinDev** [comment]
> Hi @GerkinDev,
> 
> how is life? I hope everything is fine on your side.
> 
> It took a while, and finally I've finished the process of verification and can officially accept beer donations: https://github.com/sponsors/satanTime.

Hey there ! Finally ! So, it ain't that much, but I will for sure back you much more when the fundraising of my company is done :) for now, I'm quite low on money.

Take a beer, you deserve it ;)
