### ISSUE TITLE
Creating component wrappers

### ISSUE THREAD

**Issue by ivi-hamiti** [ike18t/ng-mocks#46]
When testing onpush component to simulate change detection you need to wrap the component with another one and most of the cases have the same input/outputs. So i propose to provide a method, called WrapComponent which mocks a component with the same inputs and outputs of the original one and also wire up the outputs. The template should contain the component we want to wrap and would bind all properties from the wrapper to the inner component.

**Comment by satanTime** [comment]
Hi,

it's here, please check `MockRender`:
```typescript
const fixture = MockRender(
      `
        <tested (trigger)="myListener1($event)" [value1]="myParam1" value2="check">
          <ng-template #header>
            something as ng-template
          </ng-template>
          something as ng-content
        </tested>
      `,
      {
        myListener1: spy,
        myParam1: 'something1',
      }
    );
```
also you can always subscribe to outputs directly, behavior will stay the same as you do that in template.

**Comment by ivi-hamiti** [comment]
yes this makes sense, but effort wise it will be the same effort as to create a component as a class

```
const session = new MockSession();
const wrapperType = WrapComponent(ItemComponent);

urlHelper = session.useMock(UrlHelper);

TestBed.configureTestingModule({
	declarations: [
		wrapperType,
		ItemComponent,
		MockComponent(ItemChildComponent),
	],
	providers: [session.providers()],
});

wrapper = TestBed.createComponent(wrapperType);
```

and the wrapped component template would be something like

`<item [prop1]="prop1" [prop2]="prop2"></item>`

where all these prop can be accessed like

wrapper.componentInstance.prop1....
wrapper.componentInstance.prop2....

as the wrapper will be `ComponentFixture<ItemComponent>` even though it is a wrapper

**Comment by satanTime** [comment]
Exact case of what fixture of MockRender returns, actually it’s default behavior of TestBed itself. Not sure why you need one more wrapper around mocked component, you can access its inputs and outputs as you have on your example.

**Comment by ivi-hamiti** [comment]
In the MockRender case you have to maintain the template rendered manually, if the component inputs or outputs change, the dev will have to change all the things and not always it is type safe. 

Also to clarify the wrapper will wrap the original component, it should not be mocked as i am supposed to test the OnPush behaviour. In the previous example i am testing the `ItemComponent `and i am mocking child components `ItemChildComponent`, but as it is OnPush i am wrapping it around so test ngOnChanges behaviour. So the WrapComponent call will create the component type whill will help me.

So dom wise:
```
<wrapper> --> generated from WrapComponent
    <item> --> original, the one we need to test
        <item-child></item-child> --> generated from MockComponent
    </item>
</wrapper>
```

**Comment by satanTime** [comment]
I can't see `OnPush` in your template example.
I guess you're doing something wrong here. if You want to test that `item.OnPush` is fired, you can assert it directly as:
```typeorm
const component = TestBed.createComponent(AppItemComponent);
let stack: any = [];
component.OnPush.subscribe(value => stack.push(value));
component.someUpdate();
expect(stack).toEqual(['someValue']);
```

**Comment by ivi-hamiti** [comment]
To be clear as i may omitted the change detection strategy when describing the case, the ItemComponent has this declaration:
```
@Component({
    selector: '...',
    template: '...',
    changeDetection: ChangeDetectionStrategy.OnPush
})
export class ItemComponent....
```

**Comment by satanTime** [comment]
I see, could you create test env and share it here? I'll take a look for possible solution.

**Comment by ivi-hamiti** [comment]
so the test case is as following

```
import { ChangeDetectionStrategy, Component, DebugElement, Input } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';

@Component({
	selector: 'item-list',
	template: '{{items.length}}',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ItemListComponent {
	@Input() items: string[];
}

@Component({
	selector: 'item-list-wrapper',
	template: '<item-list [items]="items"></item-list>',
})
export class ItemListWrapperComponent {
	@Input() items: string[];
}

describe('ItemListComponent', () => {
	let wrapper: ComponentFixture<ItemListWrapperComponent>;
	let component: DebugElement;

	beforeEach(() => {
		TestBed.configureTestingModule({
			declarations: [ItemListComponent, ItemListWrapperComponent],
		});

		wrapper = TestBed.createComponent(ItemListWrapperComponent);
		wrapper.componentInstance.items = [];
		wrapper.detectChanges();

		component = wrapper.debugElement.query(By.directive(ItemListComponent));
	});

	it('should show 0 if no items', () => {
		expect(component.nativeElement.innerText).toEqual('0');
	});

	it('should show 0 if items pushed to array but not changed reference', () => {
		wrapper.componentInstance.items.push('demo');
		wrapper.detectChanges();

		expect(component.nativeElement.innerText).toEqual('0');
	});

	it('should show 1 if items array changed reference', () => {
		wrapper.componentInstance.items = ['demo'];
		wrapper.detectChanges();

		expect(component.nativeElement.innerText).toEqual('1');
	});
});
```

and the desired output would be

```
import { ChangeDetectionStrategy, Component, DebugElement, Input } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { By } from '@angular/platform-browser';

@Component({
	selector: 'item-list',
	template: '{{items.length}}',
	changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ItemListComponent {
	@Input() items: string[];
}

describe('ItemListComponent', () => {
	let wrapper: ComponentFixture<ItemListComponent>;
	let component: DebugElement;

	beforeEach(() => {
		const wrapperType = WrapComponent(ItemListComponent);
		
		TestBed.configureTestingModule({
			declarations: [wrapperType, ItemListComponent],
		});

		wrapper = TestBed.createComponent(wrapperType);
		wrapper.componentInstance.items = [];
		wrapper.detectChanges();

		component = wrapper.debugElement.query(By.directive(ItemListComponent));
	});

	it('should show 0 if no items', () => {
		expect(component.nativeElement.innerText).toEqual('0');
	});

	it('should show 0 if items pushed to array but not changed reference', () => {
		wrapper.componentInstance.items.push('demo');
		wrapper.detectChanges();

		expect(component.nativeElement.innerText).toEqual('0');
	});

	it('should show 1 if items array changed reference', () => {
		wrapper.componentInstance.items = ['demo'];
		wrapper.detectChanges();

		expect(component.nativeElement.innerText).toEqual('1');
	});
});
```

**Comment by satanTime** [comment]
Thanks! I'll check this week.

**Comment by satanTime** [comment]
So, now I see the problem.

Current solution is to use `MockRender` like that:
```typescript
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { MockRender } from 'ng-mocks';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'item-list',
  template: '{{items.length}}',
})
export class ItemListComponent {
  @Input() items: string[] = [];
}

describe('ItemListComponent', () => {
  let fixture: ComponentFixture<ItemListComponent>;
  let component: ItemListComponent;

  beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        ItemListComponent,
      ],
    });

    fixture = MockRender('<item-list [items]="items"></item-list>', {
      items: [],
    });
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should show 0 if no items', () => {
    expect(fixture.nativeElement.innerText).toEqual('0');
  });

  it('should show 0 if items pushed to array but not changed reference', () => {
    component.items.push('demo');
    fixture.detectChanges();

    expect(fixture.nativeElement.innerText).toEqual('0');
  });

  it('should show 1 if items array changed reference', () => {
    component.items = ['demo'];
    fixture.detectChanges();

    expect(fixture.nativeElement.innerText).toEqual('1');
  });
});
```
Also I'll try add new feature to pass Component directly to MockRender to add auto-mock.

**Comment by satanTime** [comment]
Please review: https://github.com/ike18t/ng-mocks/pull/47
and here example of how to wrap: https://github.com/ike18t/ng-mocks/blob/114c3276b5bf5fd2d702b63c91f726beaaebce54/e2e/on-push/on-push.spec.ts#L65-L100

**Comment by ivi-hamiti** [comment]
The approach is what i was ecpected but with only one change, i would expect the template to render all input and output bindings even if they are not defined in the params

```
 const {inputs, outputs, selector} = directiveResolver.resolve(template);
    mockedTemplate += `<${selector}`;
    if (inputs) {
      inputs.forEach((definition: string) => {
        const [property, alias] = definition.split(': ');
        if (alias && params && typeof params[alias]) {
          mockedTemplate += ` [${alias}]="${alias}"`;
        } else if (property && params && typeof params[property]) {
          mockedTemplate += ` [${property}]="${property}"`;
        }
      });
    }
    if (outputs) {
      outputs.forEach((definition: string) => {
        const [property, alias] = definition.split(': ');
        if (alias && params && typeof params[alias]) {
          mockedTemplate += ` (${alias})="${alias}($event)"`;
        } else if (property && params && typeof params[property]) {
          mockedTemplate += ` (${property})="${property}($event)"`;
        }
      });
    }
    mockedTemplate += `></${selector}>`;
```

this will be handy when you update the source component and change the bindings (add/remove/rename), add extra stuff, etc, which will reflect the changes directly to the MockRenderer template. As maintaining this will be cumbersome considering that the params is not constrained from the MComponent generic

**Comment by satanTime** [comment]
Hi @ivi-hamiti, unfortunately, it won't work and your requirements here are nice example.
In your case you expect input to be an array in the component, we have to inject an array as input in parent component, but parent component can't guess automatically about types of properties. In case if we inject undefined, it will throw an error due to wrong type.
That's why we have to pass value for properties explicitly.

**Comment by satanTime** [comment]
you can try to render your component as
```
<item-list [items]="undefined"></item-list> 
```
to reproduce the issue. Components also can expect variables of complex types too and only user knows how to provide them.

**Comment by ivi-hamiti** [comment]
my idea was to reflect to the mock type the inputs/output properties of the source component and the generated template would have been bound to the prop 

```
<item-list [items]="items"></item-list> 
```

**Comment by satanTime** [comment]
Right. How can wrapper understand that ‘items‘ should be an array?

**Comment by ivi-hamiti** [comment]
As for the types, the wrapper should not care directly.

So i was going through your code changes for MockRenderer, as i see, it is doing what expected what expected, as even we do not provide any `params`, the template is being generated correctly (which i thought will not work). One thing to clarify is that the outputs which are being listened too but are not propagated to the mock component, something like

``` typescript
// Mocked component constructor
constructor() {
    // list of outputs from the component metadata
    outputs.forEach((output: string) => {
        const self = this as {[key: string]: any};
        const handler = `${output}Hanlder`;

        self[output] = new EventEmitter<any>();
        self[handler] = ($event: any) => self[output].emit($event);
    });
}
```

also we need a overload definition for the function, as otherwise the params end up to by any while mocking the component,

``` typescript
function MockRender<TComponent extends {[key: string]: any}>(template: Type<TComponent>, params?: TComponent): ComponentFixture<TComponent>;
```

and mybe the old signature should stay as an overload for the default implementation

**Comment by satanTime** [comment]
Hi @ivi-hamiti, outputs work the same way as inputs.
```typescript
const fixture = MockRender(ItemListComponent, { 
  items: [], 
  onChange: createSpy(),
});
```
generates and renders next template
```typescript
<item-list [items]="items" (onChange)="onChange($event)"></item-list>
```
old signature is valid in case if you pass there template itself. Then you're free to define properties. When we pass component itself we should respect component's interface.
I'll double check with outputs signature.
Anyway I don't see reason to generate outputs automatically because we also don't know how will be handled by user.

**Comment by ivi-hamiti** [comment]
for the outputs thew thing with the spy makes sense

**Comment by satanTime** [comment]
Just checked, and yes, you can pass any callback to wrapper with the same name as output name from injected component.

I think the issue can be closed. Please let me know if you need anything else.

**Comment by ivi-hamiti** [comment]
Everything seems fine 👍, could you check the signature of the method? If that is fine you can close the issue

**Comment by satanTime** [comment]
Just checked, we can still pass any properties as inputs and outputs, due to custom naming for inputs and outputs like `@Input('something') other: string;` we can't predict them and anything can be passed.

**Comment by ivi-hamiti** [comment]
Yes but if you do not pass anything or you want to take advantage of intellisence the params can be anything which is not convenient as when something changes in the input params for ex. renamed, the method signature will not be able to reflect that.

**Comment by ivi-hamiti** [comment]
Also you are right too, but providing overloads would give a better experience

**Comment by ivi-hamiti** [comment]
But again if the binding you generate is based on the property name in the component, it will be safer and type safe too

**Comment by satanTime** [comment]
That's what I meant above, we can't specify types.
In the case of `@Input('something') other: string` component's interface says only about `other`, but actually you need to pass `something: string`.
Also all `@Output`s by signature are `EventEmitters`, but users pass there callbacks, not `EventEmitter`s, but with type check it will be an error too due to component's interface which expects `EventEmitter`, but not some `Function`.

**Comment by ivi-hamiti** [comment]
Totally correct. By package point of view the implementation is there, so if i would need something specific i can wrap this method by my needs, so we can close the issue
