### ISSUE TITLE
MockRender is not working when we try to spy on a service method which is called in component constructor

### ISSUE THREAD

**Issue by vinayk406** [ike18t/ng-mocks#488]
Stackblitz link to reproduce this issue
https://stackblitz.com/edit/ng-mocks-examples-gwee2q?file=app/app.component.spec.ts

**Comment by satanTime** [comment]
Hi again,

Thanks for the report.

This is expected. Because MockRender adds a middleware component. 

To spy in such cases MockInstance should be used. 

Please don't close the ticket. I'll update docs based on the issue.

**Comment by vinayk406** [comment]
@satanTime Can we add a configurable option to bypass the middleware component?

add it only when needed?

something like `MockRender(XComponent, null, { renderWithoutWrapperComponent: true  })`

**Comment by satanTime** [comment]
Something like that.

```ts
describe("mock extended component", () => {
  beforeEach(() => MockBuilder(AppComponent, AppModule));

  beforeEach(() => {
    MockInstance(AppService, 'method', jasmine.createSpy('method'));
    //
    // Or simply ngMocks.autoSpy('jasmine');
  });

  it("expect service.method to have been called", () => {
    MockRender(AppComponent);

    const service = TestBed.get(AppService);
    expect(service.method).toHaveBeenCalled();
  });
});
```

If you want to buy pass the middleware component it means you don't need `MockRender` and could use `TestBed.createComponent` instead.

The idea of `ng-mocks` and its tools is to allow to configure environment mock environment before TestBed initialization.
And then in tests to render required stuff and to do assertions.

**Comment by vinayk406** [comment]
Thanks for the explanation 👍

**Comment by satanTime** [comment]
I'll dive deeper and check if it is possible somehow to inject a component after the initialization and post an update here.

The main diff between `createComponent` and `MockRender` is that `createComponent` allow to test inputs, outputs, queries and some lifecycle hooks. And, ideally, it should be a replacement for `TestBed.createComponent`, but such cases, like you have: when there is a real service and only one of its methods should be mocked, unfortunately, doesn't work.

Might I ask to explain why you want to keep `AppService` as it is and only to mock one method?

**Comment by vinayk406** [comment]
Here is the snippet from our codebase. 

```
configureModuleBuilder(() => {
    return MockBuilder(XComponent, XModule)
        .mock(DomSanitizer, { bypassSecurityTrustUrl: v => v }, { precise: true })
        .provide([
            { provide: I18NService, useClass: I18NServiceMock },
            { provide: WindowService, useClass: WindowMock },
            { provide: Store, useClass: StoreMock },
            XActions,
        ]);
});

beforeEach(() => {
    mockWindowService = TestBed.inject(WindowService);
    store = TestBed.inject(Store);
    spyOn(store, 'dispatch');

    fixture = TestBed.createComponent(XComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
});

it('dispatches ', () => {
    expect(store.dispatch).toHaveBeenCalledWith();
});

```

When I tried to use `MockRender` instead of `TestBed.createComponent` it failed. 

It will be good if `MockRender` has the default behaviour of `createComponent`.
use the wrapper component only when needed. or an option to bypass when not required.

**Comment by satanTime** [comment]
Oh, it looks a bit confusing. `WindowService` and `Store` are mock classes already, and to mock them further could be avoided I think.

Might you share how `I18NServiceMock`, `WindowMock` and `StoreMock` look like?
I think you could use `ngMocks.defaultMock` and `MockInstance` for such a test, then its code should be shortened to a few lines.

**Comment by vinayk406** [comment]
`I18nServiceMock`, `WindowMock` and `StoreMock` are different. different spec files may require different versions of these. 

Sorry. Can't share the code for these.

**Comment by satanTime** [comment]
Sure, I totally understand this.

I'll try to find a way how to make your test working and being something like:

```ts
configureModuleBuilder(() => {
  MockInstance(DomSanitizer, 'bypassSecurityTrustUrl', v => v);
  MockInstance(I18NService, I18NServiceMock);
  MockInstance(WindowService, WindowMock);
  MockInstance(Store, StoreMock);
  MockInstance(Store, store => spyOn(store, 'dispatch'));

    return MockBuilder(XComponent, XModule).provide(XActions);
});

beforeEach(() => {
    fixture = MockRender(XComponent);
    component = fixture.point.componentInstance;
    mockWindowService = TestBed.inject(WindowService);
});

it('dispatches ', () => {
    expect(store.dispatch).toHaveBeenCalledWith();
});
```

**Comment by vinayk406** [comment]
Thank for your time on this. 
And please take a look into `memoization` of `MockRender` when you find some time.

**Comment by satanTime** [comment]
> And please take a look into `memoization` of `MockRender` when you find some time.

Could you create a separate issue and provide an example how you want it to memoize the things?

**Comment by vinayk406** [comment]
```ts
  beforeEach(() => {
    MockInstance(Store, 'dispatch', jasmine.createSpy());
    MockInstance(WindowService, 'open', jasmine.createSpy());

    mockWindowService = TestBed.inject(WindowService);
    store = TestBed.inject(Store);

    fixture = MockRender(XComponent);
    component = fixture.componentInstance;
  });
```

This snippet is working.

**Comment by vinayk406** [comment]
> > And please take a look into `memoization` of `MockRender` when you find some time.
> 
> Could you create a separate issue and provide an example how you want it to memoize the things?

Sure. will do.

**Comment by satanTime** [comment]
Hi,

the snippet you provided won't work, because calls of `TestBed.inject` are done before `MockRender`.

I think, I understood the point, which is missing in all examples above:

- `MockBuilder` describes environment for tests (should be called in `beforeEach`)
- `MockRender` initialize the environment for a test (should be called in `it`, although can be called in `beforeEach` too)

To make the example above work properly, its test should look like that:

```ts
// simplifies spy configuration
beforeEach(() => ngMocks.autoMock('jasmine'));
// beforeEach(() => MockInstance(Store, 'dispatch', jasmine.createSpy()));
// beforeEach(() => MockInstance(WindowService, 'open', jasmine.createSpy()));

// describing environment
beforeEach(() => MockBuilder(XComponent).mock(Store).mock(WindowService));

// initializing testing environment
beforeEach(() => {
  fixture = MockRender(XComponent);
  mockWindowService = TestBed.inject(WindowService);
  store = TestBed.inject(Store);
});

it('test', () => {
  expect(store.dispatch).toHaveBeenCalled();
});
```

**Comment by satanTime** [comment]
[v11.11.0](https://github.com/ike18t/ng-mocks/releases/tag/v11.11.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by satanTime** [comment]
Hi @vinayk406,

I've added an option to memories `MockRender` if it is used in `beforeAll`: https://ng-mocks.sudo.eu/api/ngMocks/faster#mockrender

**Comment by satanTime** [comment]
And this is info about default values in params: https://ng-mocks.sudo.eu/api/MockRender#params-inputs-and-outputs
