### ISSUE TITLE
How to render MatHeaderCell (or any structural directive in a ng-container)

### ISSUE THREAD

**Issue by Dji75** [ike18t/ng-mocks#569]
I was not able to render a MatHEaderCell without using deprecated __render method :/

Here is my template:
```html
      <mat-table [dataSource]="datasource" matSort>
        <ng-container matColumnDef="myColumn">
          <mat-header-cell *matHeaderCellDef>My header title</mat-header-cell>
        </ng-container>
      ...
```

Here is my test:
```
      beforeEach(() => {
        ngMocks.revealAll('[matColumnDef]');
        ngMocks.findInstances(MatHeaderCellDef).forEach((header: MockedDirective<MatHeaderCellDef>) => {
          header.__render();
        });
      });
      
      it('should display column header', () => {
        const header = ngMocks.find('mat-header-cell');
        expect(ngMocks.formatText(header)).toEqual('My header title');
      });
```

So it works but as `__render` method is deprecated, I tried to use `ngMocks.render` indeed but it seems `mat-header-cell` are not rendered :(

```typescript
        ngMocks.findAll('mat-header-cell').forEach((header) => {  <--- findAll returns empty array
          ngMocks.render(header.componentInstance, MatHeaderCellDef);
        });
```
So I got the following error:
`Error: Cannot find an element via ngMocks.find(mat-header-cell`

What's wrong, what I've missed ?

**Comment by Dji75** [comment]
`ngMocks.revealAll('[matColumnDef]');` seems to be useless, result is an empty array

**Comment by Dji75** [comment]
Damn, I got it !

```typescript
        ngMocks.findInstances(MatHeaderCellDef).forEach((header: MatHeaderCellDef) => {
          ngMocks.render(header, header);
        });
```

It was not really intuitive though even with log message ^^
` Unknown template has been passed, only TemplateRef **or a mock structural directive** are supported`

**Comment by satanTime** [comment]
Hi, thanks for the feedback.

I think your first approach makes sense. I'll try to implement it with this issue.

**Comment by satanTime** [comment]
Ah try... not much to do here, only read long and boring documentation.... sorry :)

https://ng-mocks.sudo.eu/api/ngMocks/render#directly
