### ISSUE TITLE
getters mocked as simple function

### ISSUE THREAD

**Issue by dabbid** [ike18t/ng-mocks#58]
Hello,

I've encountered problem while mocking some angular material module (`MatAutocompleteModule` in my case). In my component that implements autocomplete, I have to check if panel is opened, and if so I close it. `MaAutocompleteTrigger` directive has a `panelOpen` property that returns panel's opened status, if we look at [source code](https://github.com/angular/components/blob/master/src/material/autocomplete/autocomplete-trigger.ts#L248), we can see that this property is a getter.
Now in my spec, `this.autocompleteTrigger.panelOpen` is always evaluated to `true`, because if I log `panelOpen` property, I can see that it has been mocked as a function. And so `else` branch is never covered. I neither can do `this.autocompleteTrigger.panelOpen === true`, because then `if` branch is never covered.

The only workaround I found is:
```javascript
const trigger: MatAutocompleteTrigger = fixture.debugElement.query(By.css('input').injector.get(MatAutocompleteTrigger);
Object.defineProperty(trigger, 'panelOpen', {
  get: () => true, // or false according to the case
  configurable: true,
});
```

Any thoughts about it?

**Comment by satanTime** [comment]
There's the fix for your issue: https://github.com/ike18t/ng-mocks/pull/81
