### ISSUE TITLE
StoreModule and MockBuilder issues 

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#589]
I finally found why my tests runs not using initial (empty) initial state, this was because the spy on my metaReducer util was not taken into account, so I got previous value from sessionStorage which failed some tests :(

Here is the declaration in `AppModule`:
```typescript
    StoreModule.forRoot({}, { metaReducers: [ReducerUtils.storePersist], runtimeChecks: environment.storeRuntimeChecks }),
```
Here is how I set spy (using jasmine), prior to `MockBuilder` usage:
```typescript
      spyOn(ReducerUtils, 'storePersist').and.callFake((v) => v);
```
Maybe it can help you to see util's declaration ;)
```typescript
export abstract class ReducerUtils {
  static storePersist(reducer: ActionReducer<object>): ActionReducer<object> {
    ...
```

If I add some logs in this util, I can see them in console :-1:
If I remove metaReducers declaration, it works.

Moreover, I see another problem using `StoreDevtoolsModule`. I also have to keep it (`.keep(StoreDevtoolsModule)`). Most of tests fails because reducer function is not called even after `store.dispatch`.

you asked me before how I spy on store, here it is:
```typescript
  describe('integration', () => {
    let store: Store;
    ...
    const initTestBed = () => {
      ...
      return MockBuilder(MyComponent, [MyModule, AppModule])
        .keep(StoreRootModule)
        .keep(StoreFeatureModule)
        .keep(StoreDevtoolsModule)
        .keep(NoopAnimationsModule)
        .keep(FormsModule)
        .keep(ReactiveFormsModule);
    };
    beforeEach(initTestBed);

    beforeEach(() => {
      fixture = MockRender(MyComponent);
      store = TestBed.inject(Store);
      spyOn(store, 'dispatch').and.callThrough();
      fixture.detectChanges();
    });
```

_Originally posted by @Dji75 in https://github.com/ike18t/ng-mocks/issues/312#issuecomment-845832467_

**Comment by satanTime** [comment]
Hi @Dji75,

let's discuss the issue here. Could it be an option for you to have a call with screensharing?

**Comment by Dji75** [comment]
Thanks,  I just sent you an email

**Comment by satanTime** [comment]
Hi @Dji75, today at 16 CET then :) 

I tried to answer on your email but got a rejection email from outlook. So the same link you provided at 16 CET.

**Comment by satanTime** [comment]
@Dji75, sure, let's do it at 16.15 then.

**Comment by satanTime** [comment]
For the records.

2 issues:
- kept store and mock store dev tools have a conflict (if no actions have been dispatched)
- there a way needed to properly handle mock / kept metaReducers in a kept store

**Comment by Dji75** [comment]
In the meantime, I've added the following lines in `tests.ts` in order to exclude the modules we reasonably expecting not useful in testing suites:
```typescript
ngMocks.globalExclude(StoreDevtoolsModule);
ngMocks.globalExclude(BrowserAnimationsModule);
```

**Comment by satanTime** [comment]
Hi @Dji75,

could you test if this update works for you? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6571908/ng-mocks.zip).

The main change is that `StoreDevtoolsModule` is excluded by default.
The issue is that it has internal reducers and because the module has been mocked, the reducers are mocked too and nothing happens in the kept store. The reducers use `useExisting` and `useClass` and it makes too complicated to try to solve the whole chain in order to understand what we should keep and what we should mock. So I would leave it on shoulders of developers to decide what to do.

About `BrowserAnimationsModule`, looking forward to having a call to dig deeper into its issue.

**Comment by Dji75** [comment]
Hi @satanTime, 

Thanks for this release :)
It solved issue with `StoreDevtoolsModule` as I do not need anymore to global exclude it (explicitly), but it does not solve issue with metaReducers.

I ran my test under Firefox (headless) and Chrome (headless) with same result (still an error even if slightly différent if I don't use this version):
```
// With Firefox
        <Jasmine>
        m0Ny/</</</</<@main.js:183957:47
        invoke@polyfills.js:5612:26
        QpwO/</</ProxyZoneSpec.prototype.onInvoke@vendor.js:169407:43
        invoke@polyfills.js:5611:52
        run@polyfills.js:5374:43
        runInTestZone@vendor.js:169687:38
        wrapTestInZone/<@vendor.js:169702:24
        <Jasmine>
        invoke@polyfills.js:5612:26
        run@polyfills.js:5374:43
        scheduleResolveOrReject/<@polyfills.js:6516:36
        invokeTask@polyfills.js:5646:31
        runTask@polyfills.js:5418:47
        drainMicroTaskQueue@polyfills.js:5822:35

// With Chrome
            at <Jasmine>
            at UserContext.<anonymous> (src/app/side-panel-wrapper/daily-planning/daily-planning.component.spec.ts:692:37)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:372:1)
            at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:301:1)
``` 

The real util function given to metaReducers is still called (even with the spy)

We can have a call together if you want, same GMeet at 16PM (CET) if you are available :wink:

**Comment by satanTime** [comment]
Hi @Dji75, 

thanks for the info. Yes, let's do that today at 16 CET.
Please send me a link to the call.

**Comment by satanTime** [comment]
Add to the documentation information about `USER_PROVIDED_META_REDUCERS` in order to suppress meta reducers.

**Comment by satanTime** [comment]
[v12.1.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.1.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Dji75** [comment]
It works like a charm :+1: 
Again, thanks @satanTime

**Comment by satanTime** [comment]
Cool! Thanks for the report!
