### ISSUE TITLE
Mocking internal package components

### ISSUE THREAD

**Issue by undsoft** [ike18t/ng-mocks#60]
Hi,

This may be two issues, but I'm trying to solve 1 problem.
Out project is split into several repos and they all consume modules from a core repo, which is build as an Angular package.

The problem is that this core repo only exposes modules, but not components.
Therefore I cannot do MockComponent(SomeComponent).

When I try to mock the whole module, I get weird errors like this:

> 	Failed: Cannot read property 'reference' of null
	TypeError: Cannot read property 'reference' of null
	    at singleProviderDef (node_modules/@angular/compiler/fesm5/compiler.js:19777:1)
	    at providerDef (node_modules/@angular/compiler/fesm5/compiler.js:19729:1)
	    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder._visitProviderOrDirective (node_modules/@angular/compiler/fesm5/compiler.js:22060:1)
	    at ViewBuilder.push../node_modules/@angular/compiler/fesm5/compiler.js.ViewBuilder._visitDirective (node_modules/@angular/compiler/fesm5/compiler.js:21954:1)
	    at node_modules/@angular/compiler/fesm5/compiler.js:21879:1

I don't see anything special about this module. Some of the other modules can be mocked.

My suggestion would be to allow MockComponents to be created from selector.

**Comment by satanTime** [comment]
Hi @undsoft, might you provide more info, or maybe a code sample of the issue?
I think next setup should work for you:
```typescript
    TestBed.configureTestingModule({
      imports: [MockModule(Package1Module), MockModule(Package2Module)],
      declarations: [AnyComponentYouWantToTestComponent],
      providers: []
    });
```

**Comment by satanTime** [comment]
Hi @undsoft,

might you test the issue on 10.0.0-alpha.0 with the MockBuilder https://www.npmjs.com/package/ng-mocks/v/10.0.0-alpha.0#mockbuilder ?

**Comment by satanTime** [comment]
Hi @undsoft, have you tried beta version? 10.0.0-alpha.3 is the latest now. 
Please let me know your feedback.

**Comment by satanTime** [comment]
I'm closing the issue due to no feedback, feel free to reopen it if you meet any issues.
