### ISSUE TITLE
Mockcomponent cannot be used as an entry component.

### ISSUE THREAD

**Issue by ivarvh** [ike18t/ng-mocks#61]
I am using the ng-inline-svg library, whose module I import in my shared module. Now when I do MockModule(SharedModule), I get this error message: 

`Error: MockOfInlineSVGComponent cannot be used as an entry component.`

I saw in a different issue, that entry components were added to version 7.8.0, and I am on version 8.1.0.

Any idea what's wrong here or how I can solve this?

**Comment by xandar** [comment]
Do you have any update on this situation ?

**Comment by giampierobono** [comment]
same issue here :(

**Comment by giampierobono** [comment]
we use jest and I solved this issue by mocking the ng-inline-svg module.

1) add a root folder __mocks__
2) create a file ng-inline-svg
3) mock the module 

```javascript
import { NgModule } from '@angular/core';

const ngInlineSvgBaseMock = jest.requireActual('ng-inline-svg');
@NgModule()
class NgInlineSvgMockModule {}

ngInlineSvgBaseMock['InlineSVGModule'] = NgInlineSvgMockModule;

module.exports = ngInlineSvgBaseMock;
```

I hope it can help ;)

**Comment by shaungrady** [comment]
I'm facing this issue with the Bootstrap library:

> NgbModalBackdrop cannot be used as an entry component.

The `shallow-render` lib gets around this by providing [dontMock] and [neverMock] methods, telling the library not to mock the passed-in tokens.

[neverMock]: https://github.com/getsaf/shallow-render/wiki/Mocking#skip-mocking-globally-with-nevermock
[dontMock]: https://github.com/getsaf/shallow-render/wiki/Mocking#skip-mocking-with-dontmock

**Comment by giampierobono** [comment]
You mean to avoid mocking `NgTooltipModule`?

**Comment by shaungrady** [comment]
@giampierobono correct. So you can still mock a module, and at the same time avoid mocking predefined components/directives/services/submodules, and that no-mock blacklisting can be configured ahead of time in the test setup phase.

**Comment by satanTime** [comment]
Hi, there's fix to mock `InlineSVGComponent` correctly https://github.com/ike18t/ng-mocks/pull/82
