### ISSUE TITLE
@ContentChild wrapping fails with selectors that contain hyphens

### ISSUE THREAD

**Issue by evan-jehl** [ike18t/ng-mocks#62]
When mocking a component that has @ContentChild/@ContentChildren, if the selector for the content child contains a hyphen, which is part of standard kebab casing for Angular components, running tests with this mock component will cause an error similar to the following: Object({ ngSyntaxError: true, ngParseErrors: [ "-" is not allowed in reference names ("v *ngIf="mockRender_some-component" data-key="some-component"> (assuming the selector for ContentChild is 'some-component')

**Comment by satanTime** [comment]
Hi @evan-jehl, thanks for the info, might you provide working code sample how to reproduce the issue?

**Comment by satanTime** [comment]
or is it enough to make it `#some-component`?

**Comment by satanTime** [comment]
Currently angular says #foo-bar `'-' is not allowed in reference names`. I would say nothing should be changed.

**Comment by satanTime** [comment]
Closed as expected behaviour
