### ISSUE TITLE
A12 fails on expected `MockInstance` behavior from A11

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#625]
That is my researches: https://gist.github.com/ssergdev/f2036419ef368ae1bea2505c76dc9ce1

this test fail in v12 and not fail in v11.10

**Comment by satanTime** [comment]
Hi Sergei,

could you verify the fix ? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6572266/ng-mocks.zip)

**Comment by ssergdev** [comment]
> Hi Sergei,
> 
> could you verify the fix ? [ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6572266/ng-mocks.zip)

I tested and it works. Thank you!

**Comment by satanTime** [comment]
Awesome, thanks! I'll release it next days.

**Comment by satanTime** [comment]
[v12.1.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.1.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
