### ISSUE TITLE
MockProvider fails to handle lambdas

### ISSUE THREAD

**Issue by thepian** [ike18t/ng-mocks#630]
I want to mock an injected class (service) where I have methods and properties. Traditionally declared methods are mocked fine, but if I define one using lambda syntax, which strictly isn't a method, it isn't mocked.

```
  getTranslatedColumnDef(namespace: string, variant?: string): ColDef {
...
  }

  getStaticLookupColumnDef = (params: LookupColumnDef): ColDefPlus => ({
    cellRendererFramework: LookupCellTemplateComponent,
...
  });
```

In this case getTranslatedColumnDef is mocked while  getStaticLookupColumnDef is not.

**Comment by satanTime** [comment]
Hi @thepian, 

yep. this is how javascript behaves. `getStaticLookupColumnDef` is assigned in the ctor:

```ts
constructor() {
  this.getStaticLookupColumnDef = ...
}
```

because a mock doesn't call the ctor - nobody knows about `getStaticLookupColumnDef`.

For such a case, you can use `ngMocks.defaultMock` in `test.ts`:

```ts
ngMocks.defaultMock(SomeService, () => ({
  getStaticLookupColumnDef: jasmine.createSpy(),
}));
```

**Comment by satanTime** [comment]
Hi @thepian,

any update on this?

**Comment by satanTime** [comment]
Hi @thepian,

I'm closing the ticket. Feel free to reopen / comment it when you are available.

As I mentioned above, highly-likely this is a limitation of JS and besides the manual configuration via [`ngMocks.defaultMock`](https://ng-mocks.sudo.eu/api/ngMocks/defaultMock), not much can be done from `ng-mocks` side. 


Happy coding!
