### ISSUE TITLE
BrowserAnimationsModule to NoopAnimationsModule

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#641]
need a transparent way how to replace BrowserAnimationsModule if it hasn't been provided explicitly.

**Comment by satanTime** [comment]
Hi @Dji75,

could you verify that this version works for your without the global exclusion of animations?

[ng-mocks.zip](https://github.com/ike18t/ng-mocks/files/6593285/ng-mocks.zip)

Thank you in advance!

**Comment by Dji75** [comment]
Hi @satanTime,

Yes it worked ! ;)

I can now get rid of this, thanks ! :)

```typescript
ngMocks.globalReplace(BrowserAnimationsModule, NoopAnimationsModule);
```

**Comment by satanTime** [comment]
Cool. Thanks! Sunday is the release day then :)

**Comment by satanTime** [comment]
[v12.1.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.1.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by Dji75** [comment]
It works like a charm, thanks again :+1:
