### ISSUE TITLE
Add support for mocking inherited members

### ISSUE THREAD

**Issue by rmcc13** [ike18t/ng-mocks#69]
It looks like the `MockComponent` method does not setup methods from inherited methods. The code for setting up mock methods for both [MockDirective](https://github.com/ike18t/ng-mocks/blob/master/lib/mock-directive/mock-directive.ts#L73) and [MockComponent](https://github.com/ike18t/ng-mocks/blob/master/lib/mock-component/mock-component.ts#L96) only gets methods from the class's prototype but doesn't traverse up the prototype chain to handle inheritance.

For example, Angular Material's [MatSidenav component](https://github.com/angular/components/blob/master/src/material/sidenav/sidenav.ts#L79) extends the [MatDrawer component](https://github.com/angular/components/blob/master/src/material/sidenav/drawer.ts#L140) and methods defined on MatDrawer are not setup when mocking MatSidenav. This can cause some confusion when some methods on a type are setup and others are not.

[Here's a small stackblitz that reproduces the error](https://stackblitz.com/edit/angular-scjuj2)

**Comment by ike18t** [comment]
Neither MockComponent or MockDirective have any methods from the class's prototype. The mocked entities consist of strictly inputs & outputs. If you need further implementation detail in your mock then in your test you can query for the mocked entity and extend the instance using either a mocking framework or by plain old assignment.

**Comment by satanTime** [comment]
Hi @rmcc13, could you check if related PR works for you?
