### ISSUE TITLE
Cannot mock child component's DI services

### ISSUE THREAD

**Issue by Lonli-Lokli** [ike18t/ng-mocks#72]
Currently it's not possible to automock services inside childs as they are ignored
Steps:

Clone https://github.com/Lonli-Lokli/spectator_bug_child

Install dependencies and run
yarn test
All works
Change app.component.spec.ts:
from
ChildComponent
// MockComponent(ChildComponent)
to
// ChildComponent
MockComponent(ChildComponent)
and run yarn test
Test failed:
AppComponent › should create the app

TypeError: Cannot read property 'value' of undefined

**Comment by ike18t** [comment]
The main question I have is why would you want to? It seems like this request stems from a deeper issue of the parent component having too much context on what is going on under the hood of the child component.  

For something like a provider where it is a singleton, it would make more sense to DI it into the parent and use the provider that way which would cut out the middle-man of the child component.

**Comment by Lonli-Lokli** [comment]
In our case Child is a Grid and Parent is a View. Service inside Child is not a Singleton, it's a instance-related and provided with bunch of other services via providers for Child component declaration.
EG we have DaatsourceService and displaying somewhere in Parent number of loaded rows.

**Comment by ike18t** [comment]
Gotcha. 

MockedComponents are intended to be shallow and only consist of inputs and outputs. When I've encountered similar issues to this in the past where I need the mocked component to have additional implementation detail I typically query for the component and extend it (via a mocking lib or just assignment) prior to the behavior that has the expectation of the additional implementation existing.

**Comment by satanTime** [comment]
Hi everybody, possible fix https://github.com/ike18t/ng-mocks/pull/88
@Lonli-Lokli, could you check whether it solves your issue?
There's no spy on it, but at least it shouldn't fail.
