### ISSUE TITLE
Allow __simulateChange to MockedDirective

### ISSUE THREAD

**Issue by kekel87** [ike18t/ng-mocks#73]
Hello,

In my team we try to find the best way to test mocked MatInput directive in FormGroup.
We think the best way should be :

```typescript
TestBed.configureTestingModule({
  declarations: [
    // ...
      MockDirectives(MatInput),
  ],
  imports: [
    // ...
  ],
});

it('should ...', () => {
   const mockedDirectiveInstance = MockHelper.getDirective(
      fixture.debugElement.query(By.css('input')),
      MatInput,
    );
  mockedDirectiveInstance.__simulateChange('blabla');
  tCtx.detectChanges();
});
```
Could you please implement __simulateChange to directive or indicate us the best way to achieve this.
Thank in advance.

**Comment by satanTime** [comment]
Hi @ike18t, looks like directives and components have too many things in common. Should we combine them together while mocking through a shared base class?

**Comment by ike18t** [comment]
That makes sense to me.

**Comment by satanTime** [comment]
Hi @kekel87, could you check if https://github.com/ike18t/ng-mocks/pull/86/files works for you?
