### ISSUE TITLE
prefix dist to hide `mjs` and `cjs` from direct import.

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#761]

**Comment by satanTime** [comment]
No way to do so. `module` from `package.json` is always available as a separate import.

**Comment by GerkinDev** [comment]
Correct me if I'm wrong, but it seems kind of related to `package.json` exports discussed here : https://github.com/microsoft/TypeScript/issues/33079

**Comment by satanTime** [comment]
Hi @GerkinDev, that's great! I'll test it today, hope it is exactly what I wanted to do :)

**Comment by GerkinDev** [comment]
So subscribing to whole repo is useful sometimes :)

**Comment by satanTime** [comment]
Ahahaha, true!

**Comment by satanTime** [comment]
This is the answer: https://nodejs.org/api/packages.html#packages_conditional_exports

```json
{
  "main": "./main-require.cjs",
  "exports": {
    "import": "./main-module.js",
    "require": "./main-require.cjs"
  },
  "type": "module"
}
```

I forgot to try `type: module` when was testing it for the first time 🤦 .

**Comment by satanTime** [comment]
[v12.3.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.3.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.

**Comment by GerkinDev** [comment]
Happy you seemed to have found what you were looking for ;)

**Comment by satanTime** [comment]
Hi @GerkinDev, almost.

It worked well, but the problem is that `ng-mocks` has detection of optional dependencies via `try require catch` and I wasn't able to find the same solution with pure `import` which would support old node versions too.

So for now, I removed support for modules from `ng-mocks` and try to think over how to detect optional dependencies in a better way.

**Comment by GerkinDev** [comment]
You might still be able to try/catch `require` calls
https://nodejs.org/docs/latest-v12.x/api/module.html#module_module_createrequire_filename

Never tested it though. Moreover, you'll have to constrain the engine in `ng-mocks` installs

**Comment by satanTime** [comment]
Yep, I was thinking about that too, and ended up with commonjs only until there is a proper solution for optional imports in `module`. Because for now, it looks like a mixture of `module` and `commonjs` with a fallback to `commonjs` once I need an optional package.

**Comment by GerkinDev** [comment]
I don't think there will be any other way in ESM. ESM aims to work with static imports, and *trying* to import something but skip it if the module is not found is dynamic by essence. So I don't see any other way.

**Comment by GerkinDev** [comment]
Oh, another way might be to use `import` expressions, but it would make some functions async. https://nodejs.org/api/esm.html#esm_import_expressions

**Comment by satanTime** [comment]
Right, and only latest versions of nodejs support it, prev versions require explicit flag to enable it.
