### ISSUE TITLE
Mock ControlValueAccessor via injected NgControl

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#884]
Hey there ! Hope you are fine.

I'm trying to mock a ControlValueAccessor component that setup itself using injected NgControl, not using `provide: NG_VALUE_ACCESSOR`. My component looks like this:

```ts

@Component( {
	templateUrl: './test.component.html',
	changeDetection: ChangeDetectionStrategy.OnPush,
} )
export class TestComponent implements ControlValueAccessor {
	public get control(): FormControl {
		return this._ngControl?.control as any;
	}

	public constructor( @Self() @Inject( NgControl ) private readonly _ngControl: NgControl | null ){
		if( _ngControl ){
			_ngControl.valueAccessor = this;
		}
	}

	// #region ControlValueAccessor
	public readonly writeValue = noop;
	public readonly registerOnChange = noop
	public readonly registerOnTouched = noop
	// #endregion
}
```

Unfortunatelly, while all works fine at runtime, tests yell at me `No value accessor for form control with name: 'xxx'`

I don't know what I can do to force ng-mocks to mock my component as a CVA.

**Comment by satanTime** [comment]
Hi @GerkinDev,

it looks like mat style. `NgControl` is provided via a different directive which is real `CVA`, to make it working, you need to find this directive and to keep it along with this component.

For example, to keep `DefaultValueAccessor` or the whole `forms` module and to mark your component with its selector:

```html
<test ngDefaultControl></test>
```

**Comment by satanTime** [comment]
There is an example with `matInput`: https://github.com/ike18t/ng-mocks/blob/master/tests-angular/e2e/src/mat-input/test.spec.ts

Not exactly what you do, but might bring some light.

**Comment by GerkinDev** [comment]
I'm not sure I get it.

In my case, my component is used like this:

```html
<form [formGroup]="form" (ngSubmit)="register()">
	<app-test-control formControlName="testControl"></app-test-control>
</form>
```

I am using Angular Material. Yet, I'm not sure this pattern is specific to Material.

**Comment by satanTime** [comment]
In your case formControlName provides real `CVA` which is injected into `TestComponent` later on.

I would bet that `ReactiveFormsModule` has been mocked here. it means that `formControlName` is a string without `CVA`. Therefore, you get the error.

There are 2 options:
- keep `ReactiveFormsModule`, then `formControlName` will provide proper `CVA`.
- switch to `[formControl]="form.get('testControl')"`, then `ng-mocks` is able to detect `CVA` despite a mock of `ReactiveFormsModule`.

**Comment by satanTime** [comment]
Shaking fingers :) sorry :)

**Comment by GerkinDev** [comment]
Oh, something interesting happened. `writeValue`, `registerOnChange` & `registerOnTouched` are properties in my case, not methods, and are then not hosted on the prototype. Thus, I suspect ng-mocks to miss that this component is actually a CVA.

If I do

```ts
class TestTestComponent extends TestComponent {
	// @ts-ignore
	public writeValue(){}
	// @ts-ignore
	public registerOnChange(){}
	// @ts-ignore
	public registerOnTouched(){}
}
MockBuilder(MyComponent).mock(TestTestComponent);
```

Then it correctly detects it as a CVA

**Comment by satanTime** [comment]
Ah, you are right. Yes.

with javascript, these properties are assigned in the constructor, in a mock constructor hasn't been called, therefore no properties have been assigned and `ng-mocks` cannot detect `CVA`.

**Comment by GerkinDev** [comment]
OK my bad, thank you for the quick help :)

**Comment by satanTime** [comment]
It's JS's bad :)

**Comment by satanTime** [comment]
Let's keep the issue open, I'll update documentation about this case.

**Comment by satanTime** [comment]
[v12.5.0](https://github.com/ike18t/ng-mocks/releases/tag/v12.5.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
