### ISSUE TITLE
Make input properties writable (CoerceBoolean decorator)

### ISSUE THREAD

**Issue by GerkinDev** [ike18t/ng-mocks#896]
Hi there !

I was having troubles updating component inputs.

Such code works:

```ts
export class TestComponent {
	@Input() public readonly foo?: string;
}

const fixture = MockRender(TestComponent);
fixture.componentInstance.foo = 'asd';
```

but this one does not:

```ts
// Sligthly modified version of https://github.com/angular/angular/issues/14761#issuecomment-762812772
export const CoerceBoolean = (): PropertyDecorator =>
	( target: any, propertyKey: string | symbol ): void => {

		// double underscore used as to not pollute the single underscore private 'namespace'
		const coercedBooleanKey = `__${String( propertyKey )}`;

		Object.defineProperty( target, propertyKey, {
			// function used over fat arrow syntax to preserve the value of `this`
			get(): boolean {
				return this[coercedBooleanKey] || false;
			},
			set( booleanAttribute: boolean | unknown ): void {
				this[coercedBooleanKey] = coerceBooleanProperty( booleanAttribute );
			},
		} );
	};

export class TestComponent {
	@Input() @CoerceBoolean() public readonly foo = false;
}

const fixture = MockRender(TestComponent);
fixture.componentInstance.foo = true;
```

I've tracked down the issue up to [this point](https://github.com/ike18t/ng-mocks/blob/0266955865f1e3a7f5b2b1f5b319d7640e998865/libs/ng-mocks/src/lib/mock-service/helper.define-property-descriptor.ts#L16-L20), where the `helperExtractPropertyDescriptor` result is applied with slight modifications. But if I remove the `readonly` keyword, then it works as expected.

In my case, I'm first rendering the basic component with global inputs, and add some customizations on a test-basis before running `detectChanges` for the first time. Is it a bad pattern ?

Cheers ! :beers:

**Comment by satanTime** [comment]
Hi @GerkinDev, thanks for the info.

I'll take a look on the next weekend or following one.
Might you provide a simple test example, which I could rely on?

Usually, accessing data via `fixture.componentInstance` isn't the right way. and it would make sense to rely on `params` or `point`:

```ts
const params = {foo: true};
const fixture = MockRender(TestComponent, params);
// fixture.componentInstance.foo = true;
```

However, the code you use should proxy changes to `fixture.point.componentInstance` and if the component hasn't been mocked, then, it should still work.

**Comment by satanTime** [comment]
Hi @GerkinDev,

I hope this finds you well.

Might you confirm current status of the issue?

**Comment by satanTime** [comment]
Hi @GerkinDev,

this one I would say is expectable.
In my case, both examples don't allow to write `foo`, because it inherits `readonly` from the declaration.

A solution is to use params:

```ts
    const params = {
      foo: true,
    };
    const fixture = MockRender(TestComponent, params);
    fixture.componentInstance.foo = true;
```

In this case `MockRender`, relies on type of `params` instead of `TestComponent`.

Please let me know, if you have additional comments.
