### ISSUE TITLE
Support Angular v6

### ISSUE THREAD

**Issue by dauledk** [ike18t/ng-mocks#9]
When using this awesome library with Angular v6, it gives: 
```
npm WARN ng-mocks@5.3.0 requires a peer of @angular/core@5.x but none is installed. You must install peer dependencies yourself.
npm WARN ng-mocks@5.3.0 requires a peer of @angular/forms@5.x but none is installed. You must install peer dependencies yourself.
```

Would be awesome with support for v6.

**Comment by dauledk** [comment]
@ike18t that is insance! I like your library so much. I have no idea how I should have tested our Angular application (in a good way) without this library. Do you have some work I can help with, or maybe a small donation? I work at a startup so might be very small - but you know, just wan't to show some support for this library 😄

**Comment by dauledk** [comment]
Btw - I just installed the new version of `ng-mocks@6.0.0`, and now I get this warning: 

```
npm WARN ng-mocks@6.0.0 requires a peer of @angular/core@5.x-6.x but none is installed. You must install peer dependencies yourself.
npm WARN ng-mocks@6.0.0 requires a peer of @angular/forms@5.x-6.x but none is installed. You must install peer dependencies yourself.
```

My Angular core and form is version `6.0.1`

**Comment by ike18t** [comment]
OK.  I think npm's semantic versioning did not like 5.x-6.x for a range (for whatever reason).  I just cut a patch release.  Let me know how it goes.

Thank you for the feedback!  It definitely was painful writing unit tests prior to this (for me) with test fixtures getting stale with updates to components that were manually mocked.  If you like this lib you may also like https://www.npmjs.com/package/shallow-render which uses ng-mocks under the hood and reduces boilerplate. 

Help is always welcome!  If you'd like to take a crack at structural directive support that'd be awesome.

Let me know if there is anything I can help you with!  I'll leave this issue open until you confirm that you are good to go.

**Comment by dauledk** [comment]
The patch release worked - awesome. 

Sure - I will give shallow-render a look. Looks really awesome. I honestly think your ng-mocks is so good it should be part of Angular core. If they really mean what they say with "testing matters" 😄 

I am not super experienced with directives, but will be happy to take a look at some point.

Thanks again!
