### ISSUE TITLE
as a minor comment for docs improvement, the `dependencies` variable needs to have the `as any` thing. Otherwise, TS is not happy: https://ng-mocks.sudo.eu/extra/with-3rd-party

### ISSUE THREAD

**Issue by satanTime** [ike18t/ng-mocks#972]
as a minor comment for docs improvement, the `dependencies` variable needs to have the `as any` thing. Otherwise, TS is not happy: https://ng-mocks.sudo.eu/extra/with-3rd-party

_Originally posted by @DmitryEfimenko in https://github.com/ike18t/ng-mocks/issues/971#issuecomment-902467692_

**Comment by satanTime** [comment]
Maybe return time of the `build` could be adjusted. Anyway let's cover with an e2e test.

**Comment by DmitryEfimenko** [comment]
...and `createComponentFactory` needs to have the explicit type of the ComponentUnderTest. E2E should indeed catch that.

**Comment by satanTime** [comment]
[v13.2.0](https://github.com/ike18t/ng-mocks/releases/tag/v13.2.0) has been released and contains a fix for the issue. Feel free to reopen the issue or to submit a new one if you meet any problems.
